// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameImBotConversation = "t_im_bot_conversations"

// ImBotConversation mapped from table <t_im_bot_conversations>
type ImBotConversation struct {
	ID              int        `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	BotID           int        `gorm:"column:bot_id;type:INTEGER;not null;uniqueIndex:udx_im_bot_conversations_bid_ckey,priority:1" json:"botId"`
	ConversationKey string     `gorm:"column:conversation_key;type:TEXT;not null;uniqueIndex:udx_im_bot_conversations_bid_ckey,priority:2" json:"conversationKey"`
	ClaudeSessionID string     `gorm:"column:claude_session_id;type:TEXT;not null;default:''" json:"claudeSessionId"`
	SeenMessageIds  string     `gorm:"column:seen_message_ids;type:TEXT;not null;default:'[]'" json:"seenMessageIds"`
	LastMessageAt   *time.Time `gorm:"column:last_message_at;type:DATETIME" json:"lastMessageAt"`
	CreatedAt       time.Time  `gorm:"column:created_at;type:DATETIME;not null" json:"createdAt"`
	UpdatedAt       time.Time  `gorm:"column:updated_at;type:DATETIME;not null" json:"updatedAt"`
}

// TableName ImBotConversation's table name
func (*ImBotConversation) TableName() string {
	return TableNameImBotConversation
}
