// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"ocean-harness/server/internal/dal/enums"
	"time"
)

const TableNameImBot = "t_im_bots"

// ImBot mapped from table <t_im_bots>
type ImBot struct {
	ID           int           `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	Name         string        `gorm:"column:name;type:TEXT;not null" json:"name"`
	Channel      enums.Channel `gorm:"column:channel;type:TEXT;not null" json:"channel"`
	Credential   string        `gorm:"column:credential;type:TEXT;not null;default:'{}'" json:"credential"`
	WorkspaceID  int           `gorm:"column:workspace_id;type:INTEGER;not null" json:"workspaceId"`
	Model        string        `gorm:"column:model;type:TEXT;not null;default:''" json:"model"`
	SystemPrompt string        `gorm:"column:system_prompt;type:TEXT;not null;default:''" json:"systemPrompt"`
	AllowedTools string        `gorm:"column:allowed_tools;type:TEXT;not null;default:'[]'" json:"allowedTools"`
	AccessPolicy string        `gorm:"column:access_policy;type:TEXT;not null" json:"accessPolicy"`
	Enabled      enums.YesNo   `gorm:"column:enabled;type:TEXT;not null" json:"enabled"`
	LastError    string        `gorm:"column:last_error;type:TEXT;not null;default:''" json:"lastError"`
	CreatedAt    time.Time     `gorm:"column:created_at;type:DATETIME;not null" json:"createdAt"`
	UpdatedAt    time.Time     `gorm:"column:updated_at;type:DATETIME;not null" json:"updatedAt"`
}

// TableName ImBot's table name
func (*ImBot) TableName() string {
	return TableNameImBot
}
