// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameIssueLocalRepository = "t_issue_local_repositories"

// IssueLocalRepository mapped from table <t_issue_local_repositories>
type IssueLocalRepository struct {
	ID                int       `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	IssueID           string    `gorm:"column:issue_id;type:TEXT;not null;uniqueIndex:udx_issue_local_repositories_iid_lrid,priority:1" json:"issueId"`
	LocalRepositoryID int       `gorm:"column:local_repository_id;type:INTEGER;not null;uniqueIndex:udx_issue_local_repositories_iid_lrid,priority:2" json:"localRepositoryId"`
	RepositoryBranch  string    `gorm:"column:repository_branch;type:TEXT;not null;default:''" json:"repositoryBranch"`
	CreatedAt         time.Time `gorm:"column:created_at;type:DATETIME;not null" json:"createdAt"`
	UpdatedAt         time.Time `gorm:"column:updated_at;type:DATETIME;not null" json:"updatedAt"`
}

// TableName IssueLocalRepository's table name
func (*IssueLocalRepository) TableName() string {
	return TableNameIssueLocalRepository
}
