// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"ocean-harness/server/internal/dal/enums"
	"time"
)

const TableNameIssueAcpSession = "t_issue_acp_sessions"

// IssueAcpSession mapped from table <t_issue_acp_sessions>
type IssueAcpSession struct {
	ID           int             `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	IssueID      string          `gorm:"column:issue_id;type:TEXT;not null;uniqueIndex:udx_issue_acp_sessions_issue_id,priority:1" json:"issueId"`
	AgentCode    enums.AgentCode `gorm:"column:agent_code;type:TEXT;not null;default:''" json:"agentCode"`
	AcpSessionID string          `gorm:"column:acp_session_id;type:TEXT;not null;default:''" json:"acpSessionId"`
	LastError    string          `gorm:"column:last_error;type:TEXT;not null;default:''" json:"lastError"`
	CreatedAt    time.Time       `gorm:"column:created_at;type:DATETIME;not null" json:"createdAt"`
	UpdatedAt    time.Time       `gorm:"column:updated_at;type:DATETIME;not null" json:"updatedAt"`
}

// TableName IssueAcpSession's table name
func (*IssueAcpSession) TableName() string {
	return TableNameIssueAcpSession
}
