// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWorkspaceProject = "t_workspace_projects"

// WorkspaceProject mapped from table <t_workspace_projects>
type WorkspaceProject struct {
	ID                         int                       `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	WorkspaceID                int                       `gorm:"column:workspace_id;type:INTEGER;not null" json:"workspaceId"`
	Name                       string                    `gorm:"column:name;type:TEXT;not null" json:"name"`
	Description                string                    `gorm:"column:description;type:TEXT;not null;default:''" json:"description"`
	Emoji                      string                    `gorm:"column:emoji;type:TEXT;not null;default:''" json:"emoji"`
	CreatedAt                  time.Time                 `gorm:"column:created_at;type:DATETIME;not null" json:"createdAt"`
	UpdatedAt                  time.Time                 `gorm:"column:updated_at;type:DATETIME;not null" json:"updatedAt"`
	ProjectIssueList           []*ProjectIssue           `gorm:"foreignKey:ProjectID;references:ID" json:"projectIssueList,omitempty"`
	ProjectLocalRepositoryList []*ProjectLocalRepository `gorm:"foreignKey:WorkspaceProjectID;references:ID" json:"projectLocalRepositoryList,omitempty"`
}

// TableName WorkspaceProject's table name
func (*WorkspaceProject) TableName() string {
	return TableNameWorkspaceProject
}
