// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWorkspaceType = "t_workspace_types"

// WorkspaceType mapped from table <t_workspace_types>
type WorkspaceType struct {
	ID          int       `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	WorkspaceID int       `gorm:"column:workspace_id;type:INTEGER;not null" json:"workspaceId"`
	Name        string    `gorm:"column:name;type:TEXT;not null" json:"name"`
	Color       string    `gorm:"column:color;type:TEXT;not null;default:''" json:"color"`
	Description string    `gorm:"column:description;type:TEXT;not null;default:''" json:"description"`
	SortOrder   float64   `gorm:"column:sort_order;type:REAL;not null" json:"sortOrder"`
	CreatedAt   time.Time `gorm:"column:created_at;type:DATETIME;not null" json:"createdAt"`
	UpdatedAt   time.Time `gorm:"column:updated_at;type:DATETIME;not null" json:"updatedAt"`
}

// TableName WorkspaceType's table name
func (*WorkspaceType) TableName() string {
	return TableNameWorkspaceType
}
