// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameIssueLabel = "t_issue_labels"

// IssueLabel mapped from table <t_issue_labels>
type IssueLabel struct {
	ID        int            `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	IssueID   string         `gorm:"column:issue_id;type:TEXT;not null;uniqueIndex:udx_issue_labels_issue_id_label_id,priority:1" json:"issueId"`
	LabelID   int            `gorm:"column:label_id;type:INTEGER;not null;uniqueIndex:udx_issue_labels_issue_id_label_id,priority:2" json:"labelId"`
	CreatedAt time.Time      `gorm:"column:created_at;type:DATETIME;not null" json:"createdAt"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:DATETIME;not null" json:"updatedAt"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:DATETIME" json:"deletedAt"`
}

// TableName IssueLabel's table name
func (*IssueLabel) TableName() string {
	return TableNameIssueLabel
}
