// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLocalRepository = "t_local_repositories"

// LocalRepository mapped from table <t_local_repositories>
type LocalRepository struct {
	ID                int       `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	Name              string    `gorm:"column:name;type:TEXT;not null" json:"name"`
	LocalDir          string    `gorm:"column:local_dir;type:TEXT;not null;uniqueIndex:udx_local_repositories_local_dir,priority:1" json:"localDir"`
	Description       string    `gorm:"column:description;type:TEXT;not null;default:''" json:"description"`
	SubDirList        string    `gorm:"column:sub_dir_list;type:TEXT;not null;default:'[]'" json:"subDirList"`
	RemoteURL         string    `gorm:"column:remote_url;type:TEXT;not null;default:''" json:"remoteUrl"`
	CurrentBranch     string    `gorm:"column:current_branch;type:TEXT;not null;default:''" json:"currentBranch"`
	LastCommitAt      int       `gorm:"column:last_commit_at;type:INTEGER;not null" json:"lastCommitAt"`
	LastCommitMessage string    `gorm:"column:last_commit_message;type:TEXT;not null;default:''" json:"lastCommitMessage"`
	CreatedAt         time.Time `gorm:"column:created_at;type:DATETIME;not null" json:"createdAt"`
	UpdatedAt         time.Time `gorm:"column:updated_at;type:DATETIME;not null" json:"updatedAt"`
	DefaultBranch     string    `gorm:"column:default_branch;type:TEXT;not null;default:''" json:"defaultBranch"`
}

// TableName LocalRepository's table name
func (*LocalRepository) TableName() string {
	return TableNameLocalRepository
}
