// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
	"we-claude-terminal/go-server/internal/dal/enums"

	"gorm.io/gorm"
)

const TableNameProjectState = "t_project_states"

// ProjectState mapped from table <t_project_states>
type ProjectState struct {
	ID             int              `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	ProjectID      int              `gorm:"column:project_id;type:INTEGER;not null;uniqueIndex:udx_project_states_proj_group_state,priority:1" json:"projectId"`
	WorkspaceID    int              `gorm:"column:workspace_id;type:INTEGER;not null" json:"workspaceId"`
	StateGroupCode enums.StateGroup `gorm:"column:state_group_code;type:TEXT;not null;uniqueIndex:udx_project_states_proj_group_state,priority:2" json:"stateGroupCode"`
	StateCode      string           `gorm:"column:state_code;type:TEXT;not null;uniqueIndex:udx_project_states_proj_group_state,priority:3" json:"stateCode"`
	SortOrder      float64          `gorm:"column:sort_order;type:REAL;not null" json:"sortOrder"`
	IsDefault      enums.YesNo      `gorm:"column:is_default;type:TEXT;not null" json:"isDefault"`
	CreatedAt      time.Time        `gorm:"column:created_at;type:DATETIME;not null" json:"createdAt"`
	UpdatedAt      time.Time        `gorm:"column:updated_at;type:DATETIME;not null" json:"updatedAt"`
	DeletedAt      gorm.DeletedAt   `gorm:"column:deleted_at;type:DATETIME" json:"deletedAt"`
}

// TableName ProjectState's table name
func (*ProjectState) TableName() string {
	return TableNameProjectState
}
