// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameWorkspace = "t_workspaces"

// Workspace mapped from table <t_workspaces>
type Workspace struct {
	ID                   int                 `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	Name                 string              `gorm:"column:name;type:TEXT;not null" json:"name"`
	Slug                 string              `gorm:"column:slug;type:TEXT;not null;uniqueIndex:udx_workspaces_slug,priority:1" json:"slug"`
	Description          string              `gorm:"column:description;type:TEXT;not null;default:''" json:"description"`
	CreatedAt            time.Time           `gorm:"column:created_at;type:DATETIME;not null" json:"createdAt"`
	UpdatedAt            time.Time           `gorm:"column:updated_at;type:DATETIME;not null" json:"updatedAt"`
	DeletedAt            gorm.DeletedAt      `gorm:"column:deleted_at;type:DATETIME" json:"deletedAt"`
	WorktreeRoot         string              `gorm:"column:worktree_root;type:TEXT;not null;default:''" json:"worktreeRoot"`
	WorkspaceProjectList []*WorkspaceProject `gorm:"foreignKey:WorkspaceID;references:ID" json:"workspaceProjectList,omitempty"`
	WorkspaceLabelList   []*WorkspaceLabel   `gorm:"foreignKey:WorkspaceID;references:ID" json:"workspaceLabelList,omitempty"`
}

// TableName Workspace's table name
func (*Workspace) TableName() string {
	return TableNameWorkspace
}
