// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameWorkspaceLabel = "t_workspace_labels"

// WorkspaceLabel mapped from table <t_workspace_labels>
type WorkspaceLabel struct {
	ID          int            `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	WorkspaceID int            `gorm:"column:workspace_id;type:INTEGER;not null" json:"workspaceId"`
	ProjectID   int            `gorm:"column:project_id;type:INTEGER" json:"projectId"`
	Name        string         `gorm:"column:name;type:TEXT;not null" json:"name"`
	Color       string         `gorm:"column:color;type:TEXT;not null;default:''" json:"color"`
	Description string         `gorm:"column:description;type:TEXT;not null;default:''" json:"description"`
	SortOrder   float64        `gorm:"column:sort_order;type:REAL;not null" json:"sortOrder"`
	CreatedAt   time.Time      `gorm:"column:created_at;type:DATETIME;not null" json:"createdAt"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:DATETIME;not null" json:"updatedAt"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:DATETIME" json:"deletedAt"`
}

// TableName WorkspaceLabel's table name
func (*WorkspaceLabel) TableName() string {
	return TableNameWorkspaceLabel
}
