// Auto-generated by tauri-specta. DO NOT EDIT.
// Regenerate via `pnpm gen:bindings`.
// Source of truth: src-tauri/src/shared/types.rs + #[tauri::command] signatures.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	showPanelWindow: (navigateTo: string | null) => typedError<null, string>(__TAURI_INVOKE("show_panel_window", { navigateTo })),
	getClaudeSessions: () => typedError<ClaudeSessionInfo[], string>(__TAURI_INVOKE("get_claude_sessions")),
	/**
	 *  手动刷新会话列表：触发全量重扫并广播 claude-sessions:changed，
	 *  订阅该事件的前端（panel 的 ClaudeSessionsPage 页、pet_claude_sessions_summary、pet_claude_sessions_task）自动收到新快照。
	 *  force_git=true：手动刷新强制重算空闲会话的 GitPending，立即反映最新 git 状态。
	 */
	refreshSessions: () => typedError<null, string>(__TAURI_INVOKE("refresh_sessions")),
	/**
	 *  跳转到 pid 对应的宿主终端会话。
	 *  成功返回 Ok(())；失败 emit `claude-sessions:nav-failed` 事件，
	 *  前端据 NavErr.kind 渲染差异化 toast。
	 */
	navigateToClaudeSession: (pid: number) => typedError<null, string>(__TAURI_INVOKE("navigate_to_claude_session", { pid })),
	/**
	 *  用指定编辑器打开项目目录。
	 * 
	 *  **macOS**：GUI 应用从 Dock/Finder 启动时继承的 PATH 仅 `/usr/bin:/bin:/usr/sbin:/sbin`，
	 *  不含 `/usr/local/bin`——直接 spawn `code` / `idea` CLI 会 ENOENT（用户在终端手动执行
	 *  `code` 能用是因为 shell 读 ~/.zshrc 补全了 PATH；从 .app bundle 启动则不走 shell 流程）。
	 *  改用 macOS 原生 `open -a <App>`：`open` 在 /usr/bin 不依赖 PATH，由 LaunchServices 解析
	 *  应用。IDEA 应用名因版本而异（CE/Ultimate/EDU），依次尝试候选名，首个成功即返回。
	 * 
	 *  **Windows / Linux**：GUI 应用继承的 PATH 通常含编辑器安装目录（VSCode 安装时默认勾选
	 *  Add to PATH，IDEA 由 JetBrains Toolbox 创建 shell link），直接走 `code` / `idea` CLI 即可。
	 * 
	 *  editor 仅允许 "vscode" / "idea"；应用未安装 / 启动失败返回 Err(String)，前端 warn。
	 */
	openInEditor: (editor: string, cwd: string) => typedError<null, string>(__TAURI_INVOKE("open_in_editor", { editor, cwd })),
	/**
	 *  判断 cwd 是否 Java 项目（Maven pom.xml 或 Gradle build.gradle/build.gradle.kts）。
	 *  前端据此在非 Java 项目下禁用 IDEA（VSCode 在任何项目下都可用）。
	 */
	isJavaProject: (cwd: string) => __TAURI_INVOKE<boolean>("is_java_project", { cwd }),
	/**
	 *  用指定终端打开目录。仅 macOS 支持；terminal 仅允许 "iterm2" / "terminal"。
	 *  有窗口则新建 Tab，无窗口则新建窗口，并 cd 到指定目录。
	 *  iTerm2 模式下根据 `iterm2_split_direction` 配置决定分屏方向（默认上下分屏）。
	 */
	openInTerminal: (terminal: string, dir: string) => typedError<null, string>(__TAURI_INVOKE("open_in_terminal", { terminal, dir })),
	/**  用系统文件管理器打开目录。dir 必须为存在的绝对路径。 */
	openInFileManager: (dir: string) => typedError<null, string>(__TAURI_INVOKE("open_in_file_manager", { dir })),
	/**
	 *  用系统默认应用打开任意路径（文件或目录）：macOS 对文件走默认应用、目录走 Finder。
	 *  终端链接点击（terminal_03 §3.4）的后端出口——与 open_in_file_manager 分立，
	 *  语义各自明确（后者文档注释明确「目录」，跨平台行为也不一致：explorer 对文件
	 *  是定位而非默认打开）。path 必须为非空绝对路径。
	 */
	openPath: (path: string) => typedError<null, string>(__TAURI_INVOKE("open_path", { path })),
	showPetClaudeSessionsSummaryWindow: () => typedError<null, string>(__TAURI_INVOKE("show_pet_claude_sessions_summary_window")),
	hidePetClaudeSessionsSummaryWindow: () => typedError<null, string>(__TAURI_INVOKE("hide_pet_claude_sessions_summary_window")),
	togglePetClaudeSessionsSummaryWindow: () => typedError<boolean, string>(__TAURI_INVOKE("toggle_pet_claude_sessions_summary_window")),
	/**  查询桌宠当前显隐状态。供前端启动时初始化 UI。 */
	getPetClaudeSessionsSummaryVisibilityState: () => __TAURI_INVOKE<boolean>("get_pet_claude_sessions_summary_visibility_state"),
	/**
	 *  显示 pet_claude_sessions_task 面板：仅当 pet 可见且存在待关注会话（Busy+Waiting+GitPending）时 show + 定位，
	 *  否则 hide。显隐主导权在 pet 前端（基于 claude-sessions:changed payload 的 count），
	 *  本命令作为前端驱动入口；pet 显隐命令也调用它做联动兜底。
	 * 
	 *  待关注会话口径与前端 isAttentionClaudeSession / countAttentionClaudeSessions 一致（SSOT: claudeSessionStatus.ts）。
	 *  含 GitPending：用户 commit 后空闲会话仍需展示"待提交"，与"仅活跃"语义升级为"待关注"。
	 */
	showPetClaudeSessionsTaskWindow: () => typedError<null, string>(__TAURI_INVOKE("show_pet_claude_sessions_task_window")),
	/**
	 *  隐藏 pet_claude_sessions_task 面板。pet 隐藏时由后端 hide_pet_claude_sessions_summary_window 命令联动调用，
	 *  避免孤立的悬浮列表；pet 前端 count 归零时也主动调用。
	 */
	hidePetClaudeSessionsTaskWindow: () => typedError<null, string>(__TAURI_INVOKE("hide_pet_claude_sessions_task_window")),
	/**
	 *  前端测得实际内容高度后回调，调整窗口高度并重新定位以保持与 pet 中心水平对齐。
	 *  由 PetClaudeSessionsTaskApp 的 ResizeObserver（rAF 节流）触发；窗口已可见，不需 show。
	 *  高度变化时 Y 按 panel 中心 = pet 中心重算，保证增减会话不破坏水平对齐。
	 */
	fitPetClaudeSessionsTask: (height: number | null) => typedError<null, string>(__TAURI_INVOKE("fit_pet_claude_sessions_task", { height })),
	showSettingsWindow: (navigateTo: string | null) => typedError<null, string>(__TAURI_INVOKE("show_settings_window", { navigateTo })),
	getAppConfig: (key: string) => typedError<string | null, string>(__TAURI_INVOKE("get_app_config", { key })),
	setAppConfig: (key: string, value: string) => typedError<null, string>(__TAURI_INVOKE("set_app_config", { key, value })),
	/**  查询 HTTP 服务运行态与地址。前端 ServerStatusPage 据此渲染 Switch 与服务地址，并 fetch sysinfo。 */
	httpServerStatus: () => __TAURI_INVOKE<HttpServerStatus>("http_server_status"),
	/**
	 *  开关 HTTP 服务（true=启动，false=停止）。前端 Switch 控件调用。
	 * 
	 *  开启时仅调 start_server（内部停同会话 child + spawn，不含端口清理）；
	 *  跨会话孤立进程的清理由前端在调用本命令前显式触发 `cleanup_orphan_http_server`。
	 */
	setHttpServerEnabled: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_http_server_enabled", { enabled })),
	/**
	 *  清理跨会话残留的本应用 go-server 孤立进程（app 异常退出后残留、占用端口者）。
	 * 
	 *  仅当端口占用者进程名同时含 tauri.conf identifier 与 go_server_bin（即本应用 sidecar）才 kill，
	 *  不误杀占用同端口的其它应用。前端「服务状态」页开关从关闭→开启时，应在 `set_http_server_enabled(true)`
	 *  之前调用本命令，确保端口可用，避免新 sidecar bind 失败。
	 * 
	 *  注：init 自动启动场景不调用本命令（按需求仅在服务状态页开关触发）。
	 */
	cleanupOrphanHttpServer: () => typedError<null, string>(__TAURI_INVOKE("cleanup_orphan_http_server")),
	/**
	 *  启动/复用会话（幂等）：未退出复用 + 换装 listener；已退出重起（重开语义）。
	 *  前端挂载即调本命令；输出/退出事件经 on_event Channel 流式回传。
	 */
	ptySpawn: (opts: SpawnOpts, onEvent: Channel<PtyEvent>) => typedError<PtySpawned, string>(__TAURI_INVOKE("pty_spawn", { opts, onEvent })),
	/**  键盘输入写入会话。 */
	ptyWrite: (sessionId: string, data: string) => typedError<null, string>(__TAURI_INVOKE("pty_write", { sessionId, data })),
	/**  终端尺寸变化（xterm onResize）。 */
	ptyResize: (sessionId: string, cols: number, rows: number) => typedError<null, string>(__TAURI_INVOKE("pty_resize", { sessionId, cols, rows })),
	/**  关闭单个会话（kill shell + 移出 store）。 */
	ptyShutdown: (sessionId: string) => typedError<null, string>(__TAURI_INVOKE("pty_shutdown", { sessionId })),
	/**
	 *  关闭整个 issue 的全部 pane 会话（key 以 `issueId::` 为前缀）。
	 *  issue 删除联动调用（模块 2 split 后一 issue 多 pane，防孤儿会话）。
	 */
	ptyShutdownIssue: (issueId: string) => typedError<null, string>(__TAURI_INVOKE("pty_shutdown_issue", { issueId })),
	/**  列出全部会话快照（调试/后续状态栏用）。 */
	ptyListSessions: () => __TAURI_INVOKE<PtySessionInfo[]>("pty_list_sessions"),
	/**  会话是否存在（含已退出）。前端挂载顺序：exists → 存在则 reattach，不存在才 spawn。 */
	ptyExists: (sessionId: string) => __TAURI_INVOKE<boolean>("pty_exists", { sessionId }),
	/**
	 *  本会话 shell 子进程树内是否跑着 claude（terminal_03 §3.2 按钮置灰驱动）。
	 *  进程树匹配（claude pid 沿父链找本会话 shell pid），精确到具体终端；
	 *  前端事件 + 轮询混合驱动（useClaudeRunning）。
	 *  注意：查询必须走 provider() 自持的 store（spawn 写入侧同一实例）——曾因
	 *  app.manage 出另一恒空实例致 probe 恒 false（幽灵 manage 已删，见 state.rs）。
	 */
	ptyClaudeRunning: (sessionId: string) => __TAURI_INVOKE<boolean>("pty_claude_running", { sessionId }),
	/**
	 *  重挂会话（webview 刷新/切换 issue 回切）：ring 快照随返回值送达 + 换装 listener 续流。
	 *  已退出会话照常返回（exited=true）；不存在返回 None（前端转 pty_spawn）。
	 */
	ptyReattach: (sessionId: string, onEvent: Channel<PtyEvent>) => typedError<{
	/**  会话锚点（store key，见 SpawnOpts.session_id）。 */
	sessionId: string,
	/**  会话是否已退出（true = 前端直接展示终态 + 重开按钮，不期待实时流）。 */
	exited: boolean,
	/**  ring buffer 全量拼接（scrollback 重载，已按 UTF-8 边界切分保证合法）。 */
	scrollback: string,
} | null, string>(__TAURI_INVOKE("pty_reattach", { sessionId, onEvent })),
	/**
	 *  创建工作目录（mkdir -p 语义）。用于终端 spawn 前目录不存在时一键创建 + 重试。
	 *  校验路径非空绝对路径后 std::fs::create_dir_all。
	 */
	createDirectory: (path: string) => typedError<null, string>(__TAURI_INVOKE("create_directory", { path })),
	/**
	 *  Tauri 命令：前端 spawn 前调用（幂等）。cwd = 工作区目录
	 *  （`${workspace_base_dir}/${issueId}`，usePtySession 派生先例）。
	 */
	ensureWorkspaceHooks: (cwd: string) => typedError<null, string>(__TAURI_INVOKE("ensure_workspace_hooks", { cwd })),
	/**
	 *  查询单 pane 运行时快照（T5.2 resume 查询唯一入口）：EmbeddedTerminal
	 *  「重开并启动 claude」据此取 claudeSessionId 拼 `claude --resume <id>`。
	 *  key 即 PTY session_id（issueId::paneId）；Ok(None) = 该 pane 无绑定
	 *  （hook 链路未生效或从未跑过 claude），前端回落裸 claude。
	 */
	claudeRuntimeState: (sessionId: string) => typedError<{
	/**  pane 锚点（issueId::paneId，store key）。 */
	pane: string,
	/**  transcript JSONL 绝对路径（SessionStart 绑定）。 */
	transcriptPath: string | null,
	/**  claude 会话 ID（resume 用）。 */
	claudeSessionId: string | null,
	/**  最后更新时间（毫秒时间戳）。 */
	lastUpdatedAt: number,
} | null, string>(__TAURI_INVOKE("claude_runtime_state", { sessionId })),
};

/* Constants */
export const DEFAULT_ITERM2_SPLIT_DIRECTION = "horizontal" as const;

export const DEFAULT_POLL_INTERVAL_SECS = 120 as const;

export const DEFAULT_TERMINAL_POST_OPEN_COMMAND = "" as const;

export const EVENT_APP_CONFIG_CHANGED = "app-config-changed" as const;

export const EVENT_CLAUDE_RUNTIME_CHANGED = "claude-runtime:changed" as const;

export const EVENT_CLAUDE_SESSIONS_CHANGED = "claude-sessions:changed" as const;

export const EVENT_CLAUDE_SESSION_NAV_FAILED = "claude-sessions:nav-failed" as const;

export const EVENT_HTTP_SERVER_STATE_CHANGED = "http-server:state-changed" as const;

export const EVENT_PANEL_NAVIGATE = "panel:navigate" as const;

export const EVENT_PANEL_SHOWN = "panel:shown" as const;

export const EVENT_PET_CLAUDE_SESSIONS_TASK_REFIT = "pet-claude-sessions-task:refit" as const;

export const EVENT_SETTINGS_NAVIGATE = "settings:navigate" as const;

export const HTTP_SERVER_PORT_KEY = "http_server_port" as const;

export const HTTP_SERVER_PORT_RELEASE = 9100 as const;

export const HTTP_SERVER_PORT_TEST = 9000 as const;

export const ITERM2_SPLIT_DIRECTION_KEY = "iterm2_split_direction" as const;

export const LANGUAGE_KEY = "language" as const;

export const MAX_HTTP_SERVER_PORT = 10000 as const;

export const MAX_POLL_INTERVAL_SECS = 300 as const;

export const MIN_HTTP_SERVER_PORT = 3000 as const;

export const MIN_POLL_INTERVAL_SECS = 10 as const;

export const PET_CLAUDE_SESSIONS_SUMMARY_DRAGGABLE_KEY = "pet_claude_sessions_summary_draggable" as const;

export const POLL_INTERVAL_SECS_KEY = "poll_interval_secs" as const;

export const TERMINAL_POST_OPEN_COMMAND_KEY = "terminal_post_open_command" as const;

/* Types */
/**
 *  set_app_config 命令成功后通过 `app-config-changed` 事件广播给所有窗口的载荷。
 *  订阅方（AppThemeProvider / AppI18nProvider）据此响应配置变化。
 */
export type AppConfigChangedPayload = {
	/**  变更的配置 key（与 src/shared/appConfig.ts 中的 *_KEY 常量对齐）。 */
	key: string,
	/**  新值（配置统一以字符串形式存储，订阅方按 key 自行 decode）。 */
	value: string,
};

/**
 *  runtime 状态变更事件载荷（`claude-runtime:changed`）。ingest 归一化后 emit，
 *  前端 useClaudeRunning latch 按 pane 过滤订阅（「启动 claude」按钮置灰加速）。
 */
export type ClaudeRuntimeChangedPayload = {
	/**  pane 锚点（issueId::paneId，store key）。 */
	pane: string,
	/**  transcript JSONL 绝对路径（SessionStart 绑定）。 */
	transcriptPath: string | null,
	/**  claude 会话 ID（resume 用）。 */
	claudeSessionId: string | null,
	/**  最后更新时间（毫秒时间戳）。 */
	lastUpdatedAt: number,
};

/**
 *  终端会话快照。ClaudeSessionsPage 渲染 ClaudeSessionCard 列表的数据源；
 *  PetClaudeSessionsSummaryApp 聚合所有会话取"最忙"状态作为桌宠展示态。
 */
export type ClaudeSessionInfo = {
	/**  Claude Code 进程 pid（也是 `~/.claude/sessions/<pid>.json` 的文件名）。 */
	pid: number,
	/**  Claude Code 会话 ID（uuid）。从 json 的 `sessionId` 字段读取。 */
	sessionId: string,
	/**  会话工作目录绝对路径。 */
	cwd: string,
	/**  projectName = basename(cwd)，用于 UI 展示与 AppleScript 模糊匹配。 */
	projectName: string,
	/**  会话状态（Busy/Waiting/Idle/GitPending/Dead）。 */
	status: ClaudeSessionStatus,
	/**  会话启动时间（毫秒时间戳）。对应 json 的 `startedAt`。 */
	startedAt: number,
	/**  最后一次状态更新时间（毫秒时间戳）。对应 json 的 `updatedAt`。 */
	updatedAt: number,
	/**  宿主终端应用类型，决定跳转策略。 */
	hostApp: TerminalApp,
	/**  宿主终端进程 pid（用于 AppleScript 间接定位）。 */
	hostPid: number,
	/**
	 *  宿主终端的 tty 设备路径（如 `/dev/ttys004`），AppleScript 精确匹配用。
	 *  无法识别时为空字符串。
	 */
	tty: string,
};

/**
 *  终端会话状态。直接映射 `~/.claude/sessions/<pid>.json` 里的 `status` 字段
 *  （busy/waiting/idle）外加两个本地推断状态：GitPending（空闲且有未提交改动）与
 *  Dead（进程已退出但 json 残留）。前端 ClaudeSessionCard 据此切换状态 Chip 配色与文案。
 */
export type ClaudeSessionStatus = 
/**  运行中：Claude 正在执行工具/生成回复。 */
"Busy" | 
/**  等待输入：Claude 已完成回复，等用户输入。 */
"Waiting" | 
/**  空闲：会话长时间无活动，但仍存活。 */
"Idle" | 
/**
 *  本地派生：会话空闲（base=Idle）且其 cwd 存在未提交 git 改动（含 untracked）。
 *  由 `store::rescan` 在 enrich 后二次判定，不来自 Claude json。
 *  有界过期：fs watcher 触发的 rescan（force_git=false）复用上次缓存值，
 *  poll（60s）/手动刷新（force_git=true）强制重算，避免 watcher 高频跑 git。
 */
"GitPending" | 
/**  已失效：进程已退出，json 残留。discover 阶段会过滤掉，理论上不会出现在前端。 */
"Dead";

/**
 *  HTTP 本地服务的运行态：三态，反映 sidecar 生命周期。
 *  - Stopped：未运行（从未启动 / 已停止 / 启动失败回退）
 *  - Starting：已 spawn 子进程，等待启动成败裁定（日志静默后按 PID 身份校验）
 *  - Running：自有进程已 bind 端口，HTTP 服务可 fetch
 */
export type HttpServerRunState = "stopped" | "starting" | "running";

/**
 *  HTTP 本地服务的运行态快照（http_server_status 命令返回）。
 *  前端 ServerStatusPage 据此渲染 Switch 与服务地址，并 fetch <address>/api/baseInfo/getServerRunInfo。
 *  仅出参（后端→前端），故不 derive Deserialize。
 */
export type HttpServerStatus = {
	/**  运行态（stopped/starting/running）。running 时端口已就绪，可直接 fetch，无需重试。 */
	runState: HttpServerRunState,
	/**  服务地址（http://127.0.0.1:<port>），前端 fetch getServerRunInfo 用。 */
	address: string,
	/**  监听端口（默认 dev=9000/build=9100，可由「服务配置」覆盖）。 */
	port: number,
	/**  运行模式（debug/release），与 Go gin mode 对齐。 */
	mode: string,
	/**
	 *  最近一次启动失败的详细原因（启动期进程退出 / 身份校验未通过 / 超时时填充；正常启动/停止为 None）。
	 *  run_state 为 stopped 且此字段非空时，前端「服务状态」页据此 toast 失败原因。
	 */
	startLastError: string | null,
	/**  本次启动过程的全量日志（stdout+stderr，换行拼接；仅 Starting 期间累积，启动结束即定格）。 */
	startRecentLog: string | null,
};

/**  跳转失败原因。对应前端 navigation-failed toast 文案细分。 */
export type NavErr = 
/**  宿主终端未识别（如 VSCode 内嵌 / Wezterm 等）。 */
{ kind: "unsupportedHostApp" } | 
/**  osascript 执行失败（exit code 非零）。 */
{ kind: "osaScriptFailed"; stderr: string } | 
/**  ClaudeSessionStore 找不到对应 pid 的会话（可能刚过期）。 */
{ kind: "sessionNotFound" } | 
/**  其他 IO 错误。 */
{ kind: "io"; message: string };

/**
 *  PTY → 前端 的事件（单 Channel 双分支，数据与退出同序到达）。
 *  不出现在命令签名（仅作 Channel<PtyEvent> 泛型载荷），需在 lib.rs 用 .typ::<PtyEvent>() 注册。
 */
export type PtyEvent = 
/**  终端输出（UTF-8 边界切分后的完整字符串块）。 */
{ kind: "data"; data: string } | 
/**  shell 已退出（正常 exit / 被 kill）。会话仍在 store，前端可重开（重新 spawn）。 */
{ kind: "exit" };

/**  pty_reattach 成功荷载：scrollback 随返回值一次性送达，实时流走已换装的 Channel。 */
export type PtyReattached = {
	/**  会话锚点（store key，见 SpawnOpts.session_id）。 */
	sessionId: string,
	/**  会话是否已退出（true = 前端直接展示终态 + 重开按钮，不期待实时流）。 */
	exited: boolean,
	/**  ring buffer 全量拼接（scrollback 重载，已按 UTF-8 边界切分保证合法）。 */
	scrollback: string,
};

/**  会话信息快照（pty_list_sessions 返回，调试/后续状态栏用）。 */
export type PtySessionInfo = {
	/**  会话锚点（store key，见 SpawnOpts.session_id）。 */
	sessionId: string,
	/**  会话工作目录。 */
	cwd: string,
	/**  shell 进程 pid（拿不到为 0）。 */
	pid: number,
	/**  会话是否已退出（shell 退出/被 kill 后置位；会话仍留 store 供前端重开）。 */
	exited: boolean,
	/**  spawn 时间（毫秒时间戳，远小于 2^53，精度安全）。 */
	startedAt: number,
};

/**  pty_spawn 成功荷载：会话元信息，前端挂载时直接渲染（无需再查 list）。 */
export type PtySpawned = {
	/**  会话锚点（store key，见 SpawnOpts.session_id）。 */
	sessionId: string,
	/**  会话工作目录。 */
	cwd: string,
	/**  shell 进程 pid（拿不到为 0）。 */
	pid: number,
	/**  spawn 时间（毫秒时间戳）。 */
	startedAt: number,
	/**  本次是否新起 shell（false = 复用现有会话，如 webview 刷新后重挂）。 */
	fresh: boolean,
	/**
	 *  复用会话时的 ring 快照（StrictMode 双挂载/快速重挂场景回放早期输出）；
	 *  全新 spawn 恒为空串。
	 */
	scrollback: string,
};

/**
 *  spawn 入参。cwd 由前端派生（`${workspace_base_dir}/${issueId}`），
 *  目录不存在时本模块不创建（skills 集成职责），spawn 失败自然暴露。
 */
export type SpawnOpts = {
	/**
	 *  会话锚点（store key）：main → `issueId::main`，附加 pane →
	 *  `issueId::<uuid>`（split 分割窗口，terminal_02 §3.1）。
	 */
	sessionId: string,
	/**  工作目录绝对路径。 */
	cwd: string,
	/**  初始列数（前端 xterm addon-fit 实测值）。 */
	cols: number,
	/**  初始行数。 */
	rows: number,
	/**
	 *  直接 spawn 命令（claude_orca T5.1，唯一自动执行路径）：整串命令，首
	 *  token 为 CLI 名（如 "claude"，T5.2 的 "claude --resume <id>" 同形）。
	 *  在场时无 shell 中转——PTY 直接 exec CLI（T1.4 归因 env 打标照常注入），
	 *  CLI 退出即 pane 退出（无 shell 回落，走 exited UI；跑普通命令用附加
	 *  pane）。CLI 路径经 login shell 探测解析，失败回落普通裸 shell（warn
	 *  log，用户可手动启动）。reattach/复用分支不重直启。
	 */
	directCommand?: string | null,
};

/**
 *  宿主终端应用。通过 `ps -p <ppid>` 链式反查 Claude 进程的祖先进程名得出。
 *  用于决定跳转时调用哪个 AppleScript 脚本。
 */
export type TerminalApp = "ITerm2" | "Terminal" | "IntelliJ" | 
/**
 *  本 app（we-claude-terminal）的嵌入式 PTY 终端。跳转 = 前端聚焦对应
 *  issue 终端（terminal_03 任务 6；当前跳转暂走 UnsupportedHostApp，
 *  聚焦联动在后续模块接线——但监控列表不再过滤，会话可见）。
 */
"WeTerm" | 
/**  未识别的宿主终端（如 VSCode 内嵌、Wezterm、Alacritty 等）。跳转按钮将禁用。 */
"Unknown";

/**  Y/N 布尔风格配置值。serde rename 到单字母，序列化与 specta 导出均为 "Y"/"N"。 */
export type YesNo = "Y" | "N";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

