// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                      = new(Query)
	IssueLocalRepository   *issueLocalRepository
	LocalRepository        *localRepository
	ProjectIssue           *projectIssue
	ProjectLocalRepository *projectLocalRepository
	Workspace              *workspace
	WorkspaceProject       *workspaceProject
	WorkspaceType          *workspaceType
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	IssueLocalRepository = &Q.IssueLocalRepository
	LocalRepository = &Q.LocalRepository
	ProjectIssue = &Q.ProjectIssue
	ProjectLocalRepository = &Q.ProjectLocalRepository
	Workspace = &Q.Workspace
	WorkspaceProject = &Q.WorkspaceProject
	WorkspaceType = &Q.WorkspaceType
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                     db,
		IssueLocalRepository:   newIssueLocalRepository(db, opts...),
		LocalRepository:        newLocalRepository(db, opts...),
		ProjectIssue:           newProjectIssue(db, opts...),
		ProjectLocalRepository: newProjectLocalRepository(db, opts...),
		Workspace:              newWorkspace(db, opts...),
		WorkspaceProject:       newWorkspaceProject(db, opts...),
		WorkspaceType:          newWorkspaceType(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	IssueLocalRepository   issueLocalRepository
	LocalRepository        localRepository
	ProjectIssue           projectIssue
	ProjectLocalRepository projectLocalRepository
	Workspace              workspace
	WorkspaceProject       workspaceProject
	WorkspaceType          workspaceType
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                     db,
		IssueLocalRepository:   q.IssueLocalRepository.clone(db),
		LocalRepository:        q.LocalRepository.clone(db),
		ProjectIssue:           q.ProjectIssue.clone(db),
		ProjectLocalRepository: q.ProjectLocalRepository.clone(db),
		Workspace:              q.Workspace.clone(db),
		WorkspaceProject:       q.WorkspaceProject.clone(db),
		WorkspaceType:          q.WorkspaceType.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                     db,
		IssueLocalRepository:   q.IssueLocalRepository.replaceDB(db),
		LocalRepository:        q.LocalRepository.replaceDB(db),
		ProjectIssue:           q.ProjectIssue.replaceDB(db),
		ProjectLocalRepository: q.ProjectLocalRepository.replaceDB(db),
		Workspace:              q.Workspace.replaceDB(db),
		WorkspaceProject:       q.WorkspaceProject.replaceDB(db),
		WorkspaceType:          q.WorkspaceType.replaceDB(db),
	}
}

type queryCtx struct {
	IssueLocalRepository   IIssueLocalRepositoryDo
	LocalRepository        ILocalRepositoryDo
	ProjectIssue           IProjectIssueDo
	ProjectLocalRepository IProjectLocalRepositoryDo
	Workspace              IWorkspaceDo
	WorkspaceProject       IWorkspaceProjectDo
	WorkspaceType          IWorkspaceTypeDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		IssueLocalRepository:   q.IssueLocalRepository.WithContext(ctx),
		LocalRepository:        q.LocalRepository.WithContext(ctx),
		ProjectIssue:           q.ProjectIssue.WithContext(ctx),
		ProjectLocalRepository: q.ProjectLocalRepository.WithContext(ctx),
		Workspace:              q.Workspace.WithContext(ctx),
		WorkspaceProject:       q.WorkspaceProject.WithContext(ctx),
		WorkspaceType:          q.WorkspaceType.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
