// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ocean-harness/server/internal/dal/model"
)

func newImBot(db *gorm.DB, opts ...gen.DOOption) imBot {
	_imBot := imBot{}

	_imBot.imBotDo.UseDB(db, opts...)
	_imBot.imBotDo.UseModel(&model.ImBot{})

	tableName := _imBot.imBotDo.TableName()
	_imBot.ALL = field.NewAsterisk(tableName)
	_imBot.ID = field.NewInt(tableName, "id")
	_imBot.Name = field.NewString(tableName, "name")
	_imBot.Channel = field.NewField(tableName, "channel")
	_imBot.Credential = field.NewString(tableName, "credential")
	_imBot.WorkspaceID = field.NewInt(tableName, "workspace_id")
	_imBot.AccessPolicy = field.NewString(tableName, "access_policy")
	_imBot.Enabled = field.NewField(tableName, "enabled")
	_imBot.LastError = field.NewString(tableName, "last_error")
	_imBot.CreatedAt = field.NewTime(tableName, "created_at")
	_imBot.UpdatedAt = field.NewTime(tableName, "updated_at")

	_imBot.fillFieldMap()

	return _imBot
}

type imBot struct {
	imBotDo imBotDo

	ALL          field.Asterisk
	ID           field.Int
	Name         field.String
	Channel      field.Field
	Credential   field.String
	WorkspaceID  field.Int
	AccessPolicy field.String
	Enabled      field.Field
	LastError    field.String
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (i imBot) Table(newTableName string) *imBot {
	i.imBotDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i imBot) As(alias string) *imBot {
	i.imBotDo.DO = *(i.imBotDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *imBot) updateTableName(table string) *imBot {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewInt(table, "id")
	i.Name = field.NewString(table, "name")
	i.Channel = field.NewField(table, "channel")
	i.Credential = field.NewString(table, "credential")
	i.WorkspaceID = field.NewInt(table, "workspace_id")
	i.AccessPolicy = field.NewString(table, "access_policy")
	i.Enabled = field.NewField(table, "enabled")
	i.LastError = field.NewString(table, "last_error")
	i.CreatedAt = field.NewTime(table, "created_at")
	i.UpdatedAt = field.NewTime(table, "updated_at")

	i.fillFieldMap()

	return i
}

func (i *imBot) WithContext(ctx context.Context) IImBotDo { return i.imBotDo.WithContext(ctx) }

func (i imBot) TableName() string { return i.imBotDo.TableName() }

func (i imBot) Alias() string { return i.imBotDo.Alias() }

func (i imBot) Columns(cols ...field.Expr) gen.Columns { return i.imBotDo.Columns(cols...) }

func (i *imBot) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *imBot) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 10)
	i.fieldMap["id"] = i.ID
	i.fieldMap["name"] = i.Name
	i.fieldMap["channel"] = i.Channel
	i.fieldMap["credential"] = i.Credential
	i.fieldMap["workspace_id"] = i.WorkspaceID
	i.fieldMap["access_policy"] = i.AccessPolicy
	i.fieldMap["enabled"] = i.Enabled
	i.fieldMap["last_error"] = i.LastError
	i.fieldMap["created_at"] = i.CreatedAt
	i.fieldMap["updated_at"] = i.UpdatedAt
}

func (i imBot) clone(db *gorm.DB) imBot {
	i.imBotDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i imBot) replaceDB(db *gorm.DB) imBot {
	i.imBotDo.ReplaceDB(db)
	return i
}

type imBotDo struct{ gen.DO }

type IImBotDo interface {
	gen.SubQuery
	Debug() IImBotDo
	WithContext(ctx context.Context) IImBotDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IImBotDo
	WriteDB() IImBotDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IImBotDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IImBotDo
	Not(conds ...gen.Condition) IImBotDo
	Or(conds ...gen.Condition) IImBotDo
	Select(conds ...field.Expr) IImBotDo
	Where(conds ...gen.Condition) IImBotDo
	Order(conds ...field.Expr) IImBotDo
	Distinct(cols ...field.Expr) IImBotDo
	Omit(cols ...field.Expr) IImBotDo
	Join(table schema.Tabler, on ...field.Expr) IImBotDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IImBotDo
	RightJoin(table schema.Tabler, on ...field.Expr) IImBotDo
	Group(cols ...field.Expr) IImBotDo
	Having(conds ...gen.Condition) IImBotDo
	Limit(limit int) IImBotDo
	Offset(offset int) IImBotDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IImBotDo
	Unscoped() IImBotDo
	Create(values ...*model.ImBot) error
	CreateInBatches(values []*model.ImBot, batchSize int) error
	Save(values ...*model.ImBot) error
	First() (*model.ImBot, error)
	Take() (*model.ImBot, error)
	Last() (*model.ImBot, error)
	Find() ([]*model.ImBot, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ImBot, err error)
	FindInBatches(result *[]*model.ImBot, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ImBot) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IImBotDo
	Assign(attrs ...field.AssignExpr) IImBotDo
	Joins(fields ...field.RelationField) IImBotDo
	Preload(fields ...field.RelationField) IImBotDo
	FirstOrInit() (*model.ImBot, error)
	FirstOrCreate() (*model.ImBot, error)
	FindByPage(offset int, limit int) (result []*model.ImBot, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IImBotDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i imBotDo) Debug() IImBotDo {
	return i.withDO(i.DO.Debug())
}

func (i imBotDo) WithContext(ctx context.Context) IImBotDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i imBotDo) ReadDB() IImBotDo {
	return i.Clauses(dbresolver.Read)
}

func (i imBotDo) WriteDB() IImBotDo {
	return i.Clauses(dbresolver.Write)
}

func (i imBotDo) Session(config *gorm.Session) IImBotDo {
	return i.withDO(i.DO.Session(config))
}

func (i imBotDo) Clauses(conds ...clause.Expression) IImBotDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i imBotDo) Returning(value interface{}, columns ...string) IImBotDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i imBotDo) Not(conds ...gen.Condition) IImBotDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i imBotDo) Or(conds ...gen.Condition) IImBotDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i imBotDo) Select(conds ...field.Expr) IImBotDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i imBotDo) Where(conds ...gen.Condition) IImBotDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i imBotDo) Order(conds ...field.Expr) IImBotDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i imBotDo) Distinct(cols ...field.Expr) IImBotDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i imBotDo) Omit(cols ...field.Expr) IImBotDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i imBotDo) Join(table schema.Tabler, on ...field.Expr) IImBotDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i imBotDo) LeftJoin(table schema.Tabler, on ...field.Expr) IImBotDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i imBotDo) RightJoin(table schema.Tabler, on ...field.Expr) IImBotDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i imBotDo) Group(cols ...field.Expr) IImBotDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i imBotDo) Having(conds ...gen.Condition) IImBotDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i imBotDo) Limit(limit int) IImBotDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i imBotDo) Offset(offset int) IImBotDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i imBotDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IImBotDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i imBotDo) Unscoped() IImBotDo {
	return i.withDO(i.DO.Unscoped())
}

func (i imBotDo) Create(values ...*model.ImBot) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i imBotDo) CreateInBatches(values []*model.ImBot, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i imBotDo) Save(values ...*model.ImBot) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i imBotDo) First() (*model.ImBot, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImBot), nil
	}
}

func (i imBotDo) Take() (*model.ImBot, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImBot), nil
	}
}

func (i imBotDo) Last() (*model.ImBot, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImBot), nil
	}
}

func (i imBotDo) Find() ([]*model.ImBot, error) {
	result, err := i.DO.Find()
	return result.([]*model.ImBot), err
}

func (i imBotDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ImBot, err error) {
	buf := make([]*model.ImBot, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i imBotDo) FindInBatches(result *[]*model.ImBot, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i imBotDo) Attrs(attrs ...field.AssignExpr) IImBotDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i imBotDo) Assign(attrs ...field.AssignExpr) IImBotDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i imBotDo) Joins(fields ...field.RelationField) IImBotDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i imBotDo) Preload(fields ...field.RelationField) IImBotDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i imBotDo) FirstOrInit() (*model.ImBot, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImBot), nil
	}
}

func (i imBotDo) FirstOrCreate() (*model.ImBot, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImBot), nil
	}
}

func (i imBotDo) FindByPage(offset int, limit int) (result []*model.ImBot, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i imBotDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i imBotDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i imBotDo) Delete(models ...*model.ImBot) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *imBotDo) withDO(do gen.Dao) *imBotDo {
	i.DO = *do.(*gen.DO)
	return i
}
