// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ocean-harness/server/internal/dal/model"
)

func newImBotConversation(db *gorm.DB, opts ...gen.DOOption) imBotConversation {
	_imBotConversation := imBotConversation{}

	_imBotConversation.imBotConversationDo.UseDB(db, opts...)
	_imBotConversation.imBotConversationDo.UseModel(&model.ImBotConversation{})

	tableName := _imBotConversation.imBotConversationDo.TableName()
	_imBotConversation.ALL = field.NewAsterisk(tableName)
	_imBotConversation.ID = field.NewInt(tableName, "id")
	_imBotConversation.BotID = field.NewInt(tableName, "bot_id")
	_imBotConversation.ConversationKey = field.NewString(tableName, "conversation_key")
	_imBotConversation.ClaudeSessionID = field.NewString(tableName, "claude_session_id")
	_imBotConversation.BoundIssueID = field.NewString(tableName, "bound_issue_id")
	_imBotConversation.SeenMessageIds = field.NewString(tableName, "seen_message_ids")
	_imBotConversation.LastMessageAt = field.NewTime(tableName, "last_message_at")
	_imBotConversation.CreatedAt = field.NewTime(tableName, "created_at")
	_imBotConversation.UpdatedAt = field.NewTime(tableName, "updated_at")
	_imBotConversation.LastMessageCard = field.NewString(tableName, "last_message_card")

	_imBotConversation.fillFieldMap()

	return _imBotConversation
}

type imBotConversation struct {
	imBotConversationDo imBotConversationDo

	ALL             field.Asterisk
	ID              field.Int
	BotID           field.Int
	ConversationKey field.String
	ClaudeSessionID field.String
	BoundIssueID    field.String
	SeenMessageIds  field.String
	LastMessageAt   field.Time
	CreatedAt       field.Time
	UpdatedAt       field.Time
	LastMessageCard field.String

	fieldMap map[string]field.Expr
}

func (i imBotConversation) Table(newTableName string) *imBotConversation {
	i.imBotConversationDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i imBotConversation) As(alias string) *imBotConversation {
	i.imBotConversationDo.DO = *(i.imBotConversationDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *imBotConversation) updateTableName(table string) *imBotConversation {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewInt(table, "id")
	i.BotID = field.NewInt(table, "bot_id")
	i.ConversationKey = field.NewString(table, "conversation_key")
	i.ClaudeSessionID = field.NewString(table, "claude_session_id")
	i.BoundIssueID = field.NewString(table, "bound_issue_id")
	i.SeenMessageIds = field.NewString(table, "seen_message_ids")
	i.LastMessageAt = field.NewTime(table, "last_message_at")
	i.CreatedAt = field.NewTime(table, "created_at")
	i.UpdatedAt = field.NewTime(table, "updated_at")
	i.LastMessageCard = field.NewString(table, "last_message_card")

	i.fillFieldMap()

	return i
}

func (i *imBotConversation) WithContext(ctx context.Context) IImBotConversationDo {
	return i.imBotConversationDo.WithContext(ctx)
}

func (i imBotConversation) TableName() string { return i.imBotConversationDo.TableName() }

func (i imBotConversation) Alias() string { return i.imBotConversationDo.Alias() }

func (i imBotConversation) Columns(cols ...field.Expr) gen.Columns {
	return i.imBotConversationDo.Columns(cols...)
}

func (i *imBotConversation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *imBotConversation) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 10)
	i.fieldMap["id"] = i.ID
	i.fieldMap["bot_id"] = i.BotID
	i.fieldMap["conversation_key"] = i.ConversationKey
	i.fieldMap["claude_session_id"] = i.ClaudeSessionID
	i.fieldMap["bound_issue_id"] = i.BoundIssueID
	i.fieldMap["seen_message_ids"] = i.SeenMessageIds
	i.fieldMap["last_message_at"] = i.LastMessageAt
	i.fieldMap["created_at"] = i.CreatedAt
	i.fieldMap["updated_at"] = i.UpdatedAt
	i.fieldMap["last_message_card"] = i.LastMessageCard
}

func (i imBotConversation) clone(db *gorm.DB) imBotConversation {
	i.imBotConversationDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i imBotConversation) replaceDB(db *gorm.DB) imBotConversation {
	i.imBotConversationDo.ReplaceDB(db)
	return i
}

type imBotConversationDo struct{ gen.DO }

type IImBotConversationDo interface {
	gen.SubQuery
	Debug() IImBotConversationDo
	WithContext(ctx context.Context) IImBotConversationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IImBotConversationDo
	WriteDB() IImBotConversationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IImBotConversationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IImBotConversationDo
	Not(conds ...gen.Condition) IImBotConversationDo
	Or(conds ...gen.Condition) IImBotConversationDo
	Select(conds ...field.Expr) IImBotConversationDo
	Where(conds ...gen.Condition) IImBotConversationDo
	Order(conds ...field.Expr) IImBotConversationDo
	Distinct(cols ...field.Expr) IImBotConversationDo
	Omit(cols ...field.Expr) IImBotConversationDo
	Join(table schema.Tabler, on ...field.Expr) IImBotConversationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IImBotConversationDo
	RightJoin(table schema.Tabler, on ...field.Expr) IImBotConversationDo
	Group(cols ...field.Expr) IImBotConversationDo
	Having(conds ...gen.Condition) IImBotConversationDo
	Limit(limit int) IImBotConversationDo
	Offset(offset int) IImBotConversationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IImBotConversationDo
	Unscoped() IImBotConversationDo
	Create(values ...*model.ImBotConversation) error
	CreateInBatches(values []*model.ImBotConversation, batchSize int) error
	Save(values ...*model.ImBotConversation) error
	First() (*model.ImBotConversation, error)
	Take() (*model.ImBotConversation, error)
	Last() (*model.ImBotConversation, error)
	Find() ([]*model.ImBotConversation, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ImBotConversation, err error)
	FindInBatches(result *[]*model.ImBotConversation, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ImBotConversation) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IImBotConversationDo
	Assign(attrs ...field.AssignExpr) IImBotConversationDo
	Joins(fields ...field.RelationField) IImBotConversationDo
	Preload(fields ...field.RelationField) IImBotConversationDo
	FirstOrInit() (*model.ImBotConversation, error)
	FirstOrCreate() (*model.ImBotConversation, error)
	FindByPage(offset int, limit int) (result []*model.ImBotConversation, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IImBotConversationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i imBotConversationDo) Debug() IImBotConversationDo {
	return i.withDO(i.DO.Debug())
}

func (i imBotConversationDo) WithContext(ctx context.Context) IImBotConversationDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i imBotConversationDo) ReadDB() IImBotConversationDo {
	return i.Clauses(dbresolver.Read)
}

func (i imBotConversationDo) WriteDB() IImBotConversationDo {
	return i.Clauses(dbresolver.Write)
}

func (i imBotConversationDo) Session(config *gorm.Session) IImBotConversationDo {
	return i.withDO(i.DO.Session(config))
}

func (i imBotConversationDo) Clauses(conds ...clause.Expression) IImBotConversationDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i imBotConversationDo) Returning(value interface{}, columns ...string) IImBotConversationDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i imBotConversationDo) Not(conds ...gen.Condition) IImBotConversationDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i imBotConversationDo) Or(conds ...gen.Condition) IImBotConversationDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i imBotConversationDo) Select(conds ...field.Expr) IImBotConversationDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i imBotConversationDo) Where(conds ...gen.Condition) IImBotConversationDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i imBotConversationDo) Order(conds ...field.Expr) IImBotConversationDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i imBotConversationDo) Distinct(cols ...field.Expr) IImBotConversationDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i imBotConversationDo) Omit(cols ...field.Expr) IImBotConversationDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i imBotConversationDo) Join(table schema.Tabler, on ...field.Expr) IImBotConversationDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i imBotConversationDo) LeftJoin(table schema.Tabler, on ...field.Expr) IImBotConversationDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i imBotConversationDo) RightJoin(table schema.Tabler, on ...field.Expr) IImBotConversationDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i imBotConversationDo) Group(cols ...field.Expr) IImBotConversationDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i imBotConversationDo) Having(conds ...gen.Condition) IImBotConversationDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i imBotConversationDo) Limit(limit int) IImBotConversationDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i imBotConversationDo) Offset(offset int) IImBotConversationDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i imBotConversationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IImBotConversationDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i imBotConversationDo) Unscoped() IImBotConversationDo {
	return i.withDO(i.DO.Unscoped())
}

func (i imBotConversationDo) Create(values ...*model.ImBotConversation) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i imBotConversationDo) CreateInBatches(values []*model.ImBotConversation, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i imBotConversationDo) Save(values ...*model.ImBotConversation) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i imBotConversationDo) First() (*model.ImBotConversation, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImBotConversation), nil
	}
}

func (i imBotConversationDo) Take() (*model.ImBotConversation, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImBotConversation), nil
	}
}

func (i imBotConversationDo) Last() (*model.ImBotConversation, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImBotConversation), nil
	}
}

func (i imBotConversationDo) Find() ([]*model.ImBotConversation, error) {
	result, err := i.DO.Find()
	return result.([]*model.ImBotConversation), err
}

func (i imBotConversationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ImBotConversation, err error) {
	buf := make([]*model.ImBotConversation, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i imBotConversationDo) FindInBatches(result *[]*model.ImBotConversation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i imBotConversationDo) Attrs(attrs ...field.AssignExpr) IImBotConversationDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i imBotConversationDo) Assign(attrs ...field.AssignExpr) IImBotConversationDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i imBotConversationDo) Joins(fields ...field.RelationField) IImBotConversationDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i imBotConversationDo) Preload(fields ...field.RelationField) IImBotConversationDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i imBotConversationDo) FirstOrInit() (*model.ImBotConversation, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImBotConversation), nil
	}
}

func (i imBotConversationDo) FirstOrCreate() (*model.ImBotConversation, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImBotConversation), nil
	}
}

func (i imBotConversationDo) FindByPage(offset int, limit int) (result []*model.ImBotConversation, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i imBotConversationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i imBotConversationDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i imBotConversationDo) Delete(models ...*model.ImBotConversation) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *imBotConversationDo) withDO(do gen.Dao) *imBotConversationDo {
	i.DO = *do.(*gen.DO)
	return i
}
