// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ocean-harness/server/internal/dal/model"
)

func newIssueAcpSession(db *gorm.DB, opts ...gen.DOOption) issueAcpSession {
	_issueAcpSession := issueAcpSession{}

	_issueAcpSession.issueAcpSessionDo.UseDB(db, opts...)
	_issueAcpSession.issueAcpSessionDo.UseModel(&model.IssueAcpSession{})

	tableName := _issueAcpSession.issueAcpSessionDo.TableName()
	_issueAcpSession.ALL = field.NewAsterisk(tableName)
	_issueAcpSession.ID = field.NewInt(tableName, "id")
	_issueAcpSession.IssueID = field.NewString(tableName, "issue_id")
	_issueAcpSession.AgentCode = field.NewField(tableName, "agent_code")
	_issueAcpSession.AcpSessionID = field.NewString(tableName, "acp_session_id")
	_issueAcpSession.LastError = field.NewString(tableName, "last_error")
	_issueAcpSession.CreatedAt = field.NewTime(tableName, "created_at")
	_issueAcpSession.UpdatedAt = field.NewTime(tableName, "updated_at")

	_issueAcpSession.fillFieldMap()

	return _issueAcpSession
}

type issueAcpSession struct {
	issueAcpSessionDo issueAcpSessionDo

	ALL          field.Asterisk
	ID           field.Int
	IssueID      field.String
	AgentCode    field.Field
	AcpSessionID field.String
	LastError    field.String
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (i issueAcpSession) Table(newTableName string) *issueAcpSession {
	i.issueAcpSessionDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i issueAcpSession) As(alias string) *issueAcpSession {
	i.issueAcpSessionDo.DO = *(i.issueAcpSessionDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *issueAcpSession) updateTableName(table string) *issueAcpSession {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewInt(table, "id")
	i.IssueID = field.NewString(table, "issue_id")
	i.AgentCode = field.NewField(table, "agent_code")
	i.AcpSessionID = field.NewString(table, "acp_session_id")
	i.LastError = field.NewString(table, "last_error")
	i.CreatedAt = field.NewTime(table, "created_at")
	i.UpdatedAt = field.NewTime(table, "updated_at")

	i.fillFieldMap()

	return i
}

func (i *issueAcpSession) WithContext(ctx context.Context) IIssueAcpSessionDo {
	return i.issueAcpSessionDo.WithContext(ctx)
}

func (i issueAcpSession) TableName() string { return i.issueAcpSessionDo.TableName() }

func (i issueAcpSession) Alias() string { return i.issueAcpSessionDo.Alias() }

func (i issueAcpSession) Columns(cols ...field.Expr) gen.Columns {
	return i.issueAcpSessionDo.Columns(cols...)
}

func (i *issueAcpSession) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *issueAcpSession) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 7)
	i.fieldMap["id"] = i.ID
	i.fieldMap["issue_id"] = i.IssueID
	i.fieldMap["agent_code"] = i.AgentCode
	i.fieldMap["acp_session_id"] = i.AcpSessionID
	i.fieldMap["last_error"] = i.LastError
	i.fieldMap["created_at"] = i.CreatedAt
	i.fieldMap["updated_at"] = i.UpdatedAt
}

func (i issueAcpSession) clone(db *gorm.DB) issueAcpSession {
	i.issueAcpSessionDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i issueAcpSession) replaceDB(db *gorm.DB) issueAcpSession {
	i.issueAcpSessionDo.ReplaceDB(db)
	return i
}

type issueAcpSessionDo struct{ gen.DO }

type IIssueAcpSessionDo interface {
	gen.SubQuery
	Debug() IIssueAcpSessionDo
	WithContext(ctx context.Context) IIssueAcpSessionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IIssueAcpSessionDo
	WriteDB() IIssueAcpSessionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IIssueAcpSessionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IIssueAcpSessionDo
	Not(conds ...gen.Condition) IIssueAcpSessionDo
	Or(conds ...gen.Condition) IIssueAcpSessionDo
	Select(conds ...field.Expr) IIssueAcpSessionDo
	Where(conds ...gen.Condition) IIssueAcpSessionDo
	Order(conds ...field.Expr) IIssueAcpSessionDo
	Distinct(cols ...field.Expr) IIssueAcpSessionDo
	Omit(cols ...field.Expr) IIssueAcpSessionDo
	Join(table schema.Tabler, on ...field.Expr) IIssueAcpSessionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IIssueAcpSessionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IIssueAcpSessionDo
	Group(cols ...field.Expr) IIssueAcpSessionDo
	Having(conds ...gen.Condition) IIssueAcpSessionDo
	Limit(limit int) IIssueAcpSessionDo
	Offset(offset int) IIssueAcpSessionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IIssueAcpSessionDo
	Unscoped() IIssueAcpSessionDo
	Create(values ...*model.IssueAcpSession) error
	CreateInBatches(values []*model.IssueAcpSession, batchSize int) error
	Save(values ...*model.IssueAcpSession) error
	First() (*model.IssueAcpSession, error)
	Take() (*model.IssueAcpSession, error)
	Last() (*model.IssueAcpSession, error)
	Find() ([]*model.IssueAcpSession, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.IssueAcpSession, err error)
	FindInBatches(result *[]*model.IssueAcpSession, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.IssueAcpSession) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IIssueAcpSessionDo
	Assign(attrs ...field.AssignExpr) IIssueAcpSessionDo
	Joins(fields ...field.RelationField) IIssueAcpSessionDo
	Preload(fields ...field.RelationField) IIssueAcpSessionDo
	FirstOrInit() (*model.IssueAcpSession, error)
	FirstOrCreate() (*model.IssueAcpSession, error)
	FindByPage(offset int, limit int) (result []*model.IssueAcpSession, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IIssueAcpSessionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i issueAcpSessionDo) Debug() IIssueAcpSessionDo {
	return i.withDO(i.DO.Debug())
}

func (i issueAcpSessionDo) WithContext(ctx context.Context) IIssueAcpSessionDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i issueAcpSessionDo) ReadDB() IIssueAcpSessionDo {
	return i.Clauses(dbresolver.Read)
}

func (i issueAcpSessionDo) WriteDB() IIssueAcpSessionDo {
	return i.Clauses(dbresolver.Write)
}

func (i issueAcpSessionDo) Session(config *gorm.Session) IIssueAcpSessionDo {
	return i.withDO(i.DO.Session(config))
}

func (i issueAcpSessionDo) Clauses(conds ...clause.Expression) IIssueAcpSessionDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i issueAcpSessionDo) Returning(value interface{}, columns ...string) IIssueAcpSessionDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i issueAcpSessionDo) Not(conds ...gen.Condition) IIssueAcpSessionDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i issueAcpSessionDo) Or(conds ...gen.Condition) IIssueAcpSessionDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i issueAcpSessionDo) Select(conds ...field.Expr) IIssueAcpSessionDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i issueAcpSessionDo) Where(conds ...gen.Condition) IIssueAcpSessionDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i issueAcpSessionDo) Order(conds ...field.Expr) IIssueAcpSessionDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i issueAcpSessionDo) Distinct(cols ...field.Expr) IIssueAcpSessionDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i issueAcpSessionDo) Omit(cols ...field.Expr) IIssueAcpSessionDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i issueAcpSessionDo) Join(table schema.Tabler, on ...field.Expr) IIssueAcpSessionDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i issueAcpSessionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IIssueAcpSessionDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i issueAcpSessionDo) RightJoin(table schema.Tabler, on ...field.Expr) IIssueAcpSessionDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i issueAcpSessionDo) Group(cols ...field.Expr) IIssueAcpSessionDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i issueAcpSessionDo) Having(conds ...gen.Condition) IIssueAcpSessionDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i issueAcpSessionDo) Limit(limit int) IIssueAcpSessionDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i issueAcpSessionDo) Offset(offset int) IIssueAcpSessionDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i issueAcpSessionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IIssueAcpSessionDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i issueAcpSessionDo) Unscoped() IIssueAcpSessionDo {
	return i.withDO(i.DO.Unscoped())
}

func (i issueAcpSessionDo) Create(values ...*model.IssueAcpSession) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i issueAcpSessionDo) CreateInBatches(values []*model.IssueAcpSession, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i issueAcpSessionDo) Save(values ...*model.IssueAcpSession) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i issueAcpSessionDo) First() (*model.IssueAcpSession, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.IssueAcpSession), nil
	}
}

func (i issueAcpSessionDo) Take() (*model.IssueAcpSession, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.IssueAcpSession), nil
	}
}

func (i issueAcpSessionDo) Last() (*model.IssueAcpSession, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.IssueAcpSession), nil
	}
}

func (i issueAcpSessionDo) Find() ([]*model.IssueAcpSession, error) {
	result, err := i.DO.Find()
	return result.([]*model.IssueAcpSession), err
}

func (i issueAcpSessionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.IssueAcpSession, err error) {
	buf := make([]*model.IssueAcpSession, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i issueAcpSessionDo) FindInBatches(result *[]*model.IssueAcpSession, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i issueAcpSessionDo) Attrs(attrs ...field.AssignExpr) IIssueAcpSessionDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i issueAcpSessionDo) Assign(attrs ...field.AssignExpr) IIssueAcpSessionDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i issueAcpSessionDo) Joins(fields ...field.RelationField) IIssueAcpSessionDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i issueAcpSessionDo) Preload(fields ...field.RelationField) IIssueAcpSessionDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i issueAcpSessionDo) FirstOrInit() (*model.IssueAcpSession, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.IssueAcpSession), nil
	}
}

func (i issueAcpSessionDo) FirstOrCreate() (*model.IssueAcpSession, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.IssueAcpSession), nil
	}
}

func (i issueAcpSessionDo) FindByPage(offset int, limit int) (result []*model.IssueAcpSession, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i issueAcpSessionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i issueAcpSessionDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i issueAcpSessionDo) Delete(models ...*model.IssueAcpSession) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *issueAcpSessionDo) withDO(do gen.Dao) *issueAcpSessionDo {
	i.DO = *do.(*gen.DO)
	return i
}
