// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ocean-harness/server/internal/dal/model"
)

func newWorkspaceType(db *gorm.DB, opts ...gen.DOOption) workspaceType {
	_workspaceType := workspaceType{}

	_workspaceType.workspaceTypeDo.UseDB(db, opts...)
	_workspaceType.workspaceTypeDo.UseModel(&model.WorkspaceType{})

	tableName := _workspaceType.workspaceTypeDo.TableName()
	_workspaceType.ALL = field.NewAsterisk(tableName)
	_workspaceType.ID = field.NewInt(tableName, "id")
	_workspaceType.WorkspaceID = field.NewInt(tableName, "workspace_id")
	_workspaceType.Name = field.NewString(tableName, "name")
	_workspaceType.Color = field.NewString(tableName, "color")
	_workspaceType.Description = field.NewString(tableName, "description")
	_workspaceType.SortOrder = field.NewFloat64(tableName, "sort_order")
	_workspaceType.CreatedAt = field.NewTime(tableName, "created_at")
	_workspaceType.UpdatedAt = field.NewTime(tableName, "updated_at")

	_workspaceType.fillFieldMap()

	return _workspaceType
}

type workspaceType struct {
	workspaceTypeDo workspaceTypeDo

	ALL         field.Asterisk
	ID          field.Int
	WorkspaceID field.Int
	Name        field.String
	Color       field.String
	Description field.String
	SortOrder   field.Float64
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (w workspaceType) Table(newTableName string) *workspaceType {
	w.workspaceTypeDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w workspaceType) As(alias string) *workspaceType {
	w.workspaceTypeDo.DO = *(w.workspaceTypeDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *workspaceType) updateTableName(table string) *workspaceType {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewInt(table, "id")
	w.WorkspaceID = field.NewInt(table, "workspace_id")
	w.Name = field.NewString(table, "name")
	w.Color = field.NewString(table, "color")
	w.Description = field.NewString(table, "description")
	w.SortOrder = field.NewFloat64(table, "sort_order")
	w.CreatedAt = field.NewTime(table, "created_at")
	w.UpdatedAt = field.NewTime(table, "updated_at")

	w.fillFieldMap()

	return w
}

func (w *workspaceType) WithContext(ctx context.Context) IWorkspaceTypeDo {
	return w.workspaceTypeDo.WithContext(ctx)
}

func (w workspaceType) TableName() string { return w.workspaceTypeDo.TableName() }

func (w workspaceType) Alias() string { return w.workspaceTypeDo.Alias() }

func (w workspaceType) Columns(cols ...field.Expr) gen.Columns {
	return w.workspaceTypeDo.Columns(cols...)
}

func (w *workspaceType) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *workspaceType) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 8)
	w.fieldMap["id"] = w.ID
	w.fieldMap["workspace_id"] = w.WorkspaceID
	w.fieldMap["name"] = w.Name
	w.fieldMap["color"] = w.Color
	w.fieldMap["description"] = w.Description
	w.fieldMap["sort_order"] = w.SortOrder
	w.fieldMap["created_at"] = w.CreatedAt
	w.fieldMap["updated_at"] = w.UpdatedAt
}

func (w workspaceType) clone(db *gorm.DB) workspaceType {
	w.workspaceTypeDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w workspaceType) replaceDB(db *gorm.DB) workspaceType {
	w.workspaceTypeDo.ReplaceDB(db)
	return w
}

type workspaceTypeDo struct{ gen.DO }

type IWorkspaceTypeDo interface {
	gen.SubQuery
	Debug() IWorkspaceTypeDo
	WithContext(ctx context.Context) IWorkspaceTypeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWorkspaceTypeDo
	WriteDB() IWorkspaceTypeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWorkspaceTypeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWorkspaceTypeDo
	Not(conds ...gen.Condition) IWorkspaceTypeDo
	Or(conds ...gen.Condition) IWorkspaceTypeDo
	Select(conds ...field.Expr) IWorkspaceTypeDo
	Where(conds ...gen.Condition) IWorkspaceTypeDo
	Order(conds ...field.Expr) IWorkspaceTypeDo
	Distinct(cols ...field.Expr) IWorkspaceTypeDo
	Omit(cols ...field.Expr) IWorkspaceTypeDo
	Join(table schema.Tabler, on ...field.Expr) IWorkspaceTypeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWorkspaceTypeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWorkspaceTypeDo
	Group(cols ...field.Expr) IWorkspaceTypeDo
	Having(conds ...gen.Condition) IWorkspaceTypeDo
	Limit(limit int) IWorkspaceTypeDo
	Offset(offset int) IWorkspaceTypeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWorkspaceTypeDo
	Unscoped() IWorkspaceTypeDo
	Create(values ...*model.WorkspaceType) error
	CreateInBatches(values []*model.WorkspaceType, batchSize int) error
	Save(values ...*model.WorkspaceType) error
	First() (*model.WorkspaceType, error)
	Take() (*model.WorkspaceType, error)
	Last() (*model.WorkspaceType, error)
	Find() ([]*model.WorkspaceType, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WorkspaceType, err error)
	FindInBatches(result *[]*model.WorkspaceType, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.WorkspaceType) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWorkspaceTypeDo
	Assign(attrs ...field.AssignExpr) IWorkspaceTypeDo
	Joins(fields ...field.RelationField) IWorkspaceTypeDo
	Preload(fields ...field.RelationField) IWorkspaceTypeDo
	FirstOrInit() (*model.WorkspaceType, error)
	FirstOrCreate() (*model.WorkspaceType, error)
	FindByPage(offset int, limit int) (result []*model.WorkspaceType, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWorkspaceTypeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w workspaceTypeDo) Debug() IWorkspaceTypeDo {
	return w.withDO(w.DO.Debug())
}

func (w workspaceTypeDo) WithContext(ctx context.Context) IWorkspaceTypeDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w workspaceTypeDo) ReadDB() IWorkspaceTypeDo {
	return w.Clauses(dbresolver.Read)
}

func (w workspaceTypeDo) WriteDB() IWorkspaceTypeDo {
	return w.Clauses(dbresolver.Write)
}

func (w workspaceTypeDo) Session(config *gorm.Session) IWorkspaceTypeDo {
	return w.withDO(w.DO.Session(config))
}

func (w workspaceTypeDo) Clauses(conds ...clause.Expression) IWorkspaceTypeDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w workspaceTypeDo) Returning(value interface{}, columns ...string) IWorkspaceTypeDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w workspaceTypeDo) Not(conds ...gen.Condition) IWorkspaceTypeDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w workspaceTypeDo) Or(conds ...gen.Condition) IWorkspaceTypeDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w workspaceTypeDo) Select(conds ...field.Expr) IWorkspaceTypeDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w workspaceTypeDo) Where(conds ...gen.Condition) IWorkspaceTypeDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w workspaceTypeDo) Order(conds ...field.Expr) IWorkspaceTypeDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w workspaceTypeDo) Distinct(cols ...field.Expr) IWorkspaceTypeDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w workspaceTypeDo) Omit(cols ...field.Expr) IWorkspaceTypeDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w workspaceTypeDo) Join(table schema.Tabler, on ...field.Expr) IWorkspaceTypeDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w workspaceTypeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWorkspaceTypeDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w workspaceTypeDo) RightJoin(table schema.Tabler, on ...field.Expr) IWorkspaceTypeDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w workspaceTypeDo) Group(cols ...field.Expr) IWorkspaceTypeDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w workspaceTypeDo) Having(conds ...gen.Condition) IWorkspaceTypeDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w workspaceTypeDo) Limit(limit int) IWorkspaceTypeDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w workspaceTypeDo) Offset(offset int) IWorkspaceTypeDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w workspaceTypeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWorkspaceTypeDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w workspaceTypeDo) Unscoped() IWorkspaceTypeDo {
	return w.withDO(w.DO.Unscoped())
}

func (w workspaceTypeDo) Create(values ...*model.WorkspaceType) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w workspaceTypeDo) CreateInBatches(values []*model.WorkspaceType, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w workspaceTypeDo) Save(values ...*model.WorkspaceType) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w workspaceTypeDo) First() (*model.WorkspaceType, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkspaceType), nil
	}
}

func (w workspaceTypeDo) Take() (*model.WorkspaceType, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkspaceType), nil
	}
}

func (w workspaceTypeDo) Last() (*model.WorkspaceType, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkspaceType), nil
	}
}

func (w workspaceTypeDo) Find() ([]*model.WorkspaceType, error) {
	result, err := w.DO.Find()
	return result.([]*model.WorkspaceType), err
}

func (w workspaceTypeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WorkspaceType, err error) {
	buf := make([]*model.WorkspaceType, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w workspaceTypeDo) FindInBatches(result *[]*model.WorkspaceType, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w workspaceTypeDo) Attrs(attrs ...field.AssignExpr) IWorkspaceTypeDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w workspaceTypeDo) Assign(attrs ...field.AssignExpr) IWorkspaceTypeDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w workspaceTypeDo) Joins(fields ...field.RelationField) IWorkspaceTypeDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w workspaceTypeDo) Preload(fields ...field.RelationField) IWorkspaceTypeDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w workspaceTypeDo) FirstOrInit() (*model.WorkspaceType, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkspaceType), nil
	}
}

func (w workspaceTypeDo) FirstOrCreate() (*model.WorkspaceType, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkspaceType), nil
	}
}

func (w workspaceTypeDo) FindByPage(offset int, limit int) (result []*model.WorkspaceType, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w workspaceTypeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w workspaceTypeDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w workspaceTypeDo) Delete(models ...*model.WorkspaceType) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *workspaceTypeDo) withDO(do gen.Dao) *workspaceTypeDo {
	w.DO = *do.(*gen.DO)
	return w
}
