// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"we-claude-terminal/go-server/internal/dal/model"
)

func newIssueLabel(db *gorm.DB, opts ...gen.DOOption) issueLabel {
	_issueLabel := issueLabel{}

	_issueLabel.issueLabelDo.UseDB(db, opts...)
	_issueLabel.issueLabelDo.UseModel(&model.IssueLabel{})

	tableName := _issueLabel.issueLabelDo.TableName()
	_issueLabel.ALL = field.NewAsterisk(tableName)
	_issueLabel.ID = field.NewInt(tableName, "id")
	_issueLabel.IssueID = field.NewString(tableName, "issue_id")
	_issueLabel.LabelID = field.NewInt(tableName, "label_id")
	_issueLabel.CreatedAt = field.NewTime(tableName, "created_at")
	_issueLabel.UpdatedAt = field.NewTime(tableName, "updated_at")
	_issueLabel.DeletedAt = field.NewField(tableName, "deleted_at")

	_issueLabel.fillFieldMap()

	return _issueLabel
}

type issueLabel struct {
	issueLabelDo issueLabelDo

	ALL       field.Asterisk
	ID        field.Int
	IssueID   field.String
	LabelID   field.Int
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field

	fieldMap map[string]field.Expr
}

func (i issueLabel) Table(newTableName string) *issueLabel {
	i.issueLabelDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i issueLabel) As(alias string) *issueLabel {
	i.issueLabelDo.DO = *(i.issueLabelDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *issueLabel) updateTableName(table string) *issueLabel {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewInt(table, "id")
	i.IssueID = field.NewString(table, "issue_id")
	i.LabelID = field.NewInt(table, "label_id")
	i.CreatedAt = field.NewTime(table, "created_at")
	i.UpdatedAt = field.NewTime(table, "updated_at")
	i.DeletedAt = field.NewField(table, "deleted_at")

	i.fillFieldMap()

	return i
}

func (i *issueLabel) WithContext(ctx context.Context) IIssueLabelDo {
	return i.issueLabelDo.WithContext(ctx)
}

func (i issueLabel) TableName() string { return i.issueLabelDo.TableName() }

func (i issueLabel) Alias() string { return i.issueLabelDo.Alias() }

func (i issueLabel) Columns(cols ...field.Expr) gen.Columns { return i.issueLabelDo.Columns(cols...) }

func (i *issueLabel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *issueLabel) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 6)
	i.fieldMap["id"] = i.ID
	i.fieldMap["issue_id"] = i.IssueID
	i.fieldMap["label_id"] = i.LabelID
	i.fieldMap["created_at"] = i.CreatedAt
	i.fieldMap["updated_at"] = i.UpdatedAt
	i.fieldMap["deleted_at"] = i.DeletedAt
}

func (i issueLabel) clone(db *gorm.DB) issueLabel {
	i.issueLabelDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i issueLabel) replaceDB(db *gorm.DB) issueLabel {
	i.issueLabelDo.ReplaceDB(db)
	return i
}

type issueLabelDo struct{ gen.DO }

type IIssueLabelDo interface {
	gen.SubQuery
	Debug() IIssueLabelDo
	WithContext(ctx context.Context) IIssueLabelDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IIssueLabelDo
	WriteDB() IIssueLabelDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IIssueLabelDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IIssueLabelDo
	Not(conds ...gen.Condition) IIssueLabelDo
	Or(conds ...gen.Condition) IIssueLabelDo
	Select(conds ...field.Expr) IIssueLabelDo
	Where(conds ...gen.Condition) IIssueLabelDo
	Order(conds ...field.Expr) IIssueLabelDo
	Distinct(cols ...field.Expr) IIssueLabelDo
	Omit(cols ...field.Expr) IIssueLabelDo
	Join(table schema.Tabler, on ...field.Expr) IIssueLabelDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IIssueLabelDo
	RightJoin(table schema.Tabler, on ...field.Expr) IIssueLabelDo
	Group(cols ...field.Expr) IIssueLabelDo
	Having(conds ...gen.Condition) IIssueLabelDo
	Limit(limit int) IIssueLabelDo
	Offset(offset int) IIssueLabelDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IIssueLabelDo
	Unscoped() IIssueLabelDo
	Create(values ...*model.IssueLabel) error
	CreateInBatches(values []*model.IssueLabel, batchSize int) error
	Save(values ...*model.IssueLabel) error
	First() (*model.IssueLabel, error)
	Take() (*model.IssueLabel, error)
	Last() (*model.IssueLabel, error)
	Find() ([]*model.IssueLabel, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.IssueLabel, err error)
	FindInBatches(result *[]*model.IssueLabel, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.IssueLabel) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IIssueLabelDo
	Assign(attrs ...field.AssignExpr) IIssueLabelDo
	Joins(fields ...field.RelationField) IIssueLabelDo
	Preload(fields ...field.RelationField) IIssueLabelDo
	FirstOrInit() (*model.IssueLabel, error)
	FirstOrCreate() (*model.IssueLabel, error)
	FindByPage(offset int, limit int) (result []*model.IssueLabel, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IIssueLabelDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i issueLabelDo) Debug() IIssueLabelDo {
	return i.withDO(i.DO.Debug())
}

func (i issueLabelDo) WithContext(ctx context.Context) IIssueLabelDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i issueLabelDo) ReadDB() IIssueLabelDo {
	return i.Clauses(dbresolver.Read)
}

func (i issueLabelDo) WriteDB() IIssueLabelDo {
	return i.Clauses(dbresolver.Write)
}

func (i issueLabelDo) Session(config *gorm.Session) IIssueLabelDo {
	return i.withDO(i.DO.Session(config))
}

func (i issueLabelDo) Clauses(conds ...clause.Expression) IIssueLabelDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i issueLabelDo) Returning(value interface{}, columns ...string) IIssueLabelDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i issueLabelDo) Not(conds ...gen.Condition) IIssueLabelDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i issueLabelDo) Or(conds ...gen.Condition) IIssueLabelDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i issueLabelDo) Select(conds ...field.Expr) IIssueLabelDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i issueLabelDo) Where(conds ...gen.Condition) IIssueLabelDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i issueLabelDo) Order(conds ...field.Expr) IIssueLabelDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i issueLabelDo) Distinct(cols ...field.Expr) IIssueLabelDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i issueLabelDo) Omit(cols ...field.Expr) IIssueLabelDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i issueLabelDo) Join(table schema.Tabler, on ...field.Expr) IIssueLabelDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i issueLabelDo) LeftJoin(table schema.Tabler, on ...field.Expr) IIssueLabelDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i issueLabelDo) RightJoin(table schema.Tabler, on ...field.Expr) IIssueLabelDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i issueLabelDo) Group(cols ...field.Expr) IIssueLabelDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i issueLabelDo) Having(conds ...gen.Condition) IIssueLabelDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i issueLabelDo) Limit(limit int) IIssueLabelDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i issueLabelDo) Offset(offset int) IIssueLabelDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i issueLabelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IIssueLabelDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i issueLabelDo) Unscoped() IIssueLabelDo {
	return i.withDO(i.DO.Unscoped())
}

func (i issueLabelDo) Create(values ...*model.IssueLabel) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i issueLabelDo) CreateInBatches(values []*model.IssueLabel, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i issueLabelDo) Save(values ...*model.IssueLabel) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i issueLabelDo) First() (*model.IssueLabel, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.IssueLabel), nil
	}
}

func (i issueLabelDo) Take() (*model.IssueLabel, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.IssueLabel), nil
	}
}

func (i issueLabelDo) Last() (*model.IssueLabel, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.IssueLabel), nil
	}
}

func (i issueLabelDo) Find() ([]*model.IssueLabel, error) {
	result, err := i.DO.Find()
	return result.([]*model.IssueLabel), err
}

func (i issueLabelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.IssueLabel, err error) {
	buf := make([]*model.IssueLabel, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i issueLabelDo) FindInBatches(result *[]*model.IssueLabel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i issueLabelDo) Attrs(attrs ...field.AssignExpr) IIssueLabelDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i issueLabelDo) Assign(attrs ...field.AssignExpr) IIssueLabelDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i issueLabelDo) Joins(fields ...field.RelationField) IIssueLabelDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i issueLabelDo) Preload(fields ...field.RelationField) IIssueLabelDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i issueLabelDo) FirstOrInit() (*model.IssueLabel, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.IssueLabel), nil
	}
}

func (i issueLabelDo) FirstOrCreate() (*model.IssueLabel, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.IssueLabel), nil
	}
}

func (i issueLabelDo) FindByPage(offset int, limit int) (result []*model.IssueLabel, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i issueLabelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i issueLabelDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i issueLabelDo) Delete(models ...*model.IssueLabel) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *issueLabelDo) withDO(do gen.Dao) *issueLabelDo {
	i.DO = *do.(*gen.DO)
	return i
}
