// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"we-claude-terminal/go-server/internal/dal/model"
)

func newIssueWorktree(db *gorm.DB, opts ...gen.DOOption) issueWorktree {
	_issueWorktree := issueWorktree{}

	_issueWorktree.issueWorktreeDo.UseDB(db, opts...)
	_issueWorktree.issueWorktreeDo.UseModel(&model.IssueWorktree{})

	tableName := _issueWorktree.issueWorktreeDo.TableName()
	_issueWorktree.ALL = field.NewAsterisk(tableName)
	_issueWorktree.ID = field.NewInt(tableName, "id")
	_issueWorktree.WorktreeID = field.NewString(tableName, "worktree_id")
	_issueWorktree.IssueID = field.NewInt(tableName, "issue_id")
	_issueWorktree.LocalRepositoryID = field.NewInt(tableName, "local_repository_id")
	_issueWorktree.WorktreePath = field.NewString(tableName, "worktree_path")
	_issueWorktree.WorktreeBranch = field.NewString(tableName, "worktree_branch")
	_issueWorktree.BaseBranch = field.NewString(tableName, "base_branch")
	_issueWorktree.Status = field.NewField(tableName, "status")
	_issueWorktree.CreatedAt = field.NewTime(tableName, "created_at")
	_issueWorktree.DeletedAt = field.NewField(tableName, "deleted_at")

	_issueWorktree.fillFieldMap()

	return _issueWorktree
}

type issueWorktree struct {
	issueWorktreeDo issueWorktreeDo

	ALL               field.Asterisk
	ID                field.Int
	WorktreeID        field.String
	IssueID           field.Int
	LocalRepositoryID field.Int
	WorktreePath      field.String
	WorktreeBranch    field.String
	BaseBranch        field.String
	Status            field.Field
	CreatedAt         field.Time
	DeletedAt         field.Field

	fieldMap map[string]field.Expr
}

func (i issueWorktree) Table(newTableName string) *issueWorktree {
	i.issueWorktreeDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i issueWorktree) As(alias string) *issueWorktree {
	i.issueWorktreeDo.DO = *(i.issueWorktreeDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *issueWorktree) updateTableName(table string) *issueWorktree {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewInt(table, "id")
	i.WorktreeID = field.NewString(table, "worktree_id")
	i.IssueID = field.NewInt(table, "issue_id")
	i.LocalRepositoryID = field.NewInt(table, "local_repository_id")
	i.WorktreePath = field.NewString(table, "worktree_path")
	i.WorktreeBranch = field.NewString(table, "worktree_branch")
	i.BaseBranch = field.NewString(table, "base_branch")
	i.Status = field.NewField(table, "status")
	i.CreatedAt = field.NewTime(table, "created_at")
	i.DeletedAt = field.NewField(table, "deleted_at")

	i.fillFieldMap()

	return i
}

func (i *issueWorktree) WithContext(ctx context.Context) IIssueWorktreeDo {
	return i.issueWorktreeDo.WithContext(ctx)
}

func (i issueWorktree) TableName() string { return i.issueWorktreeDo.TableName() }

func (i issueWorktree) Alias() string { return i.issueWorktreeDo.Alias() }

func (i issueWorktree) Columns(cols ...field.Expr) gen.Columns {
	return i.issueWorktreeDo.Columns(cols...)
}

func (i *issueWorktree) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *issueWorktree) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 10)
	i.fieldMap["id"] = i.ID
	i.fieldMap["worktree_id"] = i.WorktreeID
	i.fieldMap["issue_id"] = i.IssueID
	i.fieldMap["local_repository_id"] = i.LocalRepositoryID
	i.fieldMap["worktree_path"] = i.WorktreePath
	i.fieldMap["worktree_branch"] = i.WorktreeBranch
	i.fieldMap["base_branch"] = i.BaseBranch
	i.fieldMap["status"] = i.Status
	i.fieldMap["created_at"] = i.CreatedAt
	i.fieldMap["deleted_at"] = i.DeletedAt
}

func (i issueWorktree) clone(db *gorm.DB) issueWorktree {
	i.issueWorktreeDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i issueWorktree) replaceDB(db *gorm.DB) issueWorktree {
	i.issueWorktreeDo.ReplaceDB(db)
	return i
}

type issueWorktreeDo struct{ gen.DO }

type IIssueWorktreeDo interface {
	gen.SubQuery
	Debug() IIssueWorktreeDo
	WithContext(ctx context.Context) IIssueWorktreeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IIssueWorktreeDo
	WriteDB() IIssueWorktreeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IIssueWorktreeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IIssueWorktreeDo
	Not(conds ...gen.Condition) IIssueWorktreeDo
	Or(conds ...gen.Condition) IIssueWorktreeDo
	Select(conds ...field.Expr) IIssueWorktreeDo
	Where(conds ...gen.Condition) IIssueWorktreeDo
	Order(conds ...field.Expr) IIssueWorktreeDo
	Distinct(cols ...field.Expr) IIssueWorktreeDo
	Omit(cols ...field.Expr) IIssueWorktreeDo
	Join(table schema.Tabler, on ...field.Expr) IIssueWorktreeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IIssueWorktreeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IIssueWorktreeDo
	Group(cols ...field.Expr) IIssueWorktreeDo
	Having(conds ...gen.Condition) IIssueWorktreeDo
	Limit(limit int) IIssueWorktreeDo
	Offset(offset int) IIssueWorktreeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IIssueWorktreeDo
	Unscoped() IIssueWorktreeDo
	Create(values ...*model.IssueWorktree) error
	CreateInBatches(values []*model.IssueWorktree, batchSize int) error
	Save(values ...*model.IssueWorktree) error
	First() (*model.IssueWorktree, error)
	Take() (*model.IssueWorktree, error)
	Last() (*model.IssueWorktree, error)
	Find() ([]*model.IssueWorktree, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.IssueWorktree, err error)
	FindInBatches(result *[]*model.IssueWorktree, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.IssueWorktree) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IIssueWorktreeDo
	Assign(attrs ...field.AssignExpr) IIssueWorktreeDo
	Joins(fields ...field.RelationField) IIssueWorktreeDo
	Preload(fields ...field.RelationField) IIssueWorktreeDo
	FirstOrInit() (*model.IssueWorktree, error)
	FirstOrCreate() (*model.IssueWorktree, error)
	FindByPage(offset int, limit int) (result []*model.IssueWorktree, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IIssueWorktreeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i issueWorktreeDo) Debug() IIssueWorktreeDo {
	return i.withDO(i.DO.Debug())
}

func (i issueWorktreeDo) WithContext(ctx context.Context) IIssueWorktreeDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i issueWorktreeDo) ReadDB() IIssueWorktreeDo {
	return i.Clauses(dbresolver.Read)
}

func (i issueWorktreeDo) WriteDB() IIssueWorktreeDo {
	return i.Clauses(dbresolver.Write)
}

func (i issueWorktreeDo) Session(config *gorm.Session) IIssueWorktreeDo {
	return i.withDO(i.DO.Session(config))
}

func (i issueWorktreeDo) Clauses(conds ...clause.Expression) IIssueWorktreeDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i issueWorktreeDo) Returning(value interface{}, columns ...string) IIssueWorktreeDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i issueWorktreeDo) Not(conds ...gen.Condition) IIssueWorktreeDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i issueWorktreeDo) Or(conds ...gen.Condition) IIssueWorktreeDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i issueWorktreeDo) Select(conds ...field.Expr) IIssueWorktreeDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i issueWorktreeDo) Where(conds ...gen.Condition) IIssueWorktreeDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i issueWorktreeDo) Order(conds ...field.Expr) IIssueWorktreeDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i issueWorktreeDo) Distinct(cols ...field.Expr) IIssueWorktreeDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i issueWorktreeDo) Omit(cols ...field.Expr) IIssueWorktreeDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i issueWorktreeDo) Join(table schema.Tabler, on ...field.Expr) IIssueWorktreeDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i issueWorktreeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IIssueWorktreeDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i issueWorktreeDo) RightJoin(table schema.Tabler, on ...field.Expr) IIssueWorktreeDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i issueWorktreeDo) Group(cols ...field.Expr) IIssueWorktreeDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i issueWorktreeDo) Having(conds ...gen.Condition) IIssueWorktreeDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i issueWorktreeDo) Limit(limit int) IIssueWorktreeDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i issueWorktreeDo) Offset(offset int) IIssueWorktreeDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i issueWorktreeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IIssueWorktreeDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i issueWorktreeDo) Unscoped() IIssueWorktreeDo {
	return i.withDO(i.DO.Unscoped())
}

func (i issueWorktreeDo) Create(values ...*model.IssueWorktree) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i issueWorktreeDo) CreateInBatches(values []*model.IssueWorktree, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i issueWorktreeDo) Save(values ...*model.IssueWorktree) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i issueWorktreeDo) First() (*model.IssueWorktree, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.IssueWorktree), nil
	}
}

func (i issueWorktreeDo) Take() (*model.IssueWorktree, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.IssueWorktree), nil
	}
}

func (i issueWorktreeDo) Last() (*model.IssueWorktree, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.IssueWorktree), nil
	}
}

func (i issueWorktreeDo) Find() ([]*model.IssueWorktree, error) {
	result, err := i.DO.Find()
	return result.([]*model.IssueWorktree), err
}

func (i issueWorktreeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.IssueWorktree, err error) {
	buf := make([]*model.IssueWorktree, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i issueWorktreeDo) FindInBatches(result *[]*model.IssueWorktree, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i issueWorktreeDo) Attrs(attrs ...field.AssignExpr) IIssueWorktreeDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i issueWorktreeDo) Assign(attrs ...field.AssignExpr) IIssueWorktreeDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i issueWorktreeDo) Joins(fields ...field.RelationField) IIssueWorktreeDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i issueWorktreeDo) Preload(fields ...field.RelationField) IIssueWorktreeDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i issueWorktreeDo) FirstOrInit() (*model.IssueWorktree, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.IssueWorktree), nil
	}
}

func (i issueWorktreeDo) FirstOrCreate() (*model.IssueWorktree, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.IssueWorktree), nil
	}
}

func (i issueWorktreeDo) FindByPage(offset int, limit int) (result []*model.IssueWorktree, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i issueWorktreeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i issueWorktreeDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i issueWorktreeDo) Delete(models ...*model.IssueWorktree) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *issueWorktreeDo) withDO(do gen.Dao) *issueWorktreeDo {
	i.DO = *do.(*gen.DO)
	return i
}
