// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"we-claude-terminal/go-server/internal/dal/model"
)

func newIssueLocalRepository(db *gorm.DB, opts ...gen.DOOption) issueLocalRepository {
	_issueLocalRepository := issueLocalRepository{}

	_issueLocalRepository.issueLocalRepositoryDo.UseDB(db, opts...)
	_issueLocalRepository.issueLocalRepositoryDo.UseModel(&model.IssueLocalRepository{})

	tableName := _issueLocalRepository.issueLocalRepositoryDo.TableName()
	_issueLocalRepository.ALL = field.NewAsterisk(tableName)
	_issueLocalRepository.ID = field.NewInt(tableName, "id")
	_issueLocalRepository.IssueID = field.NewString(tableName, "issue_id")
	_issueLocalRepository.LocalRepositoryID = field.NewInt(tableName, "local_repository_id")
	_issueLocalRepository.RepositoryBranch = field.NewString(tableName, "repository_branch")
	_issueLocalRepository.CreatedAt = field.NewTime(tableName, "created_at")
	_issueLocalRepository.UpdatedAt = field.NewTime(tableName, "updated_at")

	_issueLocalRepository.fillFieldMap()

	return _issueLocalRepository
}

type issueLocalRepository struct {
	issueLocalRepositoryDo issueLocalRepositoryDo

	ALL               field.Asterisk
	ID                field.Int
	IssueID           field.String
	LocalRepositoryID field.Int
	RepositoryBranch  field.String
	CreatedAt         field.Time
	UpdatedAt         field.Time

	fieldMap map[string]field.Expr
}

func (i issueLocalRepository) Table(newTableName string) *issueLocalRepository {
	i.issueLocalRepositoryDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i issueLocalRepository) As(alias string) *issueLocalRepository {
	i.issueLocalRepositoryDo.DO = *(i.issueLocalRepositoryDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *issueLocalRepository) updateTableName(table string) *issueLocalRepository {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewInt(table, "id")
	i.IssueID = field.NewString(table, "issue_id")
	i.LocalRepositoryID = field.NewInt(table, "local_repository_id")
	i.RepositoryBranch = field.NewString(table, "repository_branch")
	i.CreatedAt = field.NewTime(table, "created_at")
	i.UpdatedAt = field.NewTime(table, "updated_at")

	i.fillFieldMap()

	return i
}

func (i *issueLocalRepository) WithContext(ctx context.Context) IIssueLocalRepositoryDo {
	return i.issueLocalRepositoryDo.WithContext(ctx)
}

func (i issueLocalRepository) TableName() string { return i.issueLocalRepositoryDo.TableName() }

func (i issueLocalRepository) Alias() string { return i.issueLocalRepositoryDo.Alias() }

func (i issueLocalRepository) Columns(cols ...field.Expr) gen.Columns {
	return i.issueLocalRepositoryDo.Columns(cols...)
}

func (i *issueLocalRepository) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *issueLocalRepository) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 6)
	i.fieldMap["id"] = i.ID
	i.fieldMap["issue_id"] = i.IssueID
	i.fieldMap["local_repository_id"] = i.LocalRepositoryID
	i.fieldMap["repository_branch"] = i.RepositoryBranch
	i.fieldMap["created_at"] = i.CreatedAt
	i.fieldMap["updated_at"] = i.UpdatedAt
}

func (i issueLocalRepository) clone(db *gorm.DB) issueLocalRepository {
	i.issueLocalRepositoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i issueLocalRepository) replaceDB(db *gorm.DB) issueLocalRepository {
	i.issueLocalRepositoryDo.ReplaceDB(db)
	return i
}

type issueLocalRepositoryDo struct{ gen.DO }

type IIssueLocalRepositoryDo interface {
	gen.SubQuery
	Debug() IIssueLocalRepositoryDo
	WithContext(ctx context.Context) IIssueLocalRepositoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IIssueLocalRepositoryDo
	WriteDB() IIssueLocalRepositoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IIssueLocalRepositoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IIssueLocalRepositoryDo
	Not(conds ...gen.Condition) IIssueLocalRepositoryDo
	Or(conds ...gen.Condition) IIssueLocalRepositoryDo
	Select(conds ...field.Expr) IIssueLocalRepositoryDo
	Where(conds ...gen.Condition) IIssueLocalRepositoryDo
	Order(conds ...field.Expr) IIssueLocalRepositoryDo
	Distinct(cols ...field.Expr) IIssueLocalRepositoryDo
	Omit(cols ...field.Expr) IIssueLocalRepositoryDo
	Join(table schema.Tabler, on ...field.Expr) IIssueLocalRepositoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IIssueLocalRepositoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IIssueLocalRepositoryDo
	Group(cols ...field.Expr) IIssueLocalRepositoryDo
	Having(conds ...gen.Condition) IIssueLocalRepositoryDo
	Limit(limit int) IIssueLocalRepositoryDo
	Offset(offset int) IIssueLocalRepositoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IIssueLocalRepositoryDo
	Unscoped() IIssueLocalRepositoryDo
	Create(values ...*model.IssueLocalRepository) error
	CreateInBatches(values []*model.IssueLocalRepository, batchSize int) error
	Save(values ...*model.IssueLocalRepository) error
	First() (*model.IssueLocalRepository, error)
	Take() (*model.IssueLocalRepository, error)
	Last() (*model.IssueLocalRepository, error)
	Find() ([]*model.IssueLocalRepository, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.IssueLocalRepository, err error)
	FindInBatches(result *[]*model.IssueLocalRepository, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.IssueLocalRepository) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IIssueLocalRepositoryDo
	Assign(attrs ...field.AssignExpr) IIssueLocalRepositoryDo
	Joins(fields ...field.RelationField) IIssueLocalRepositoryDo
	Preload(fields ...field.RelationField) IIssueLocalRepositoryDo
	FirstOrInit() (*model.IssueLocalRepository, error)
	FirstOrCreate() (*model.IssueLocalRepository, error)
	FindByPage(offset int, limit int) (result []*model.IssueLocalRepository, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IIssueLocalRepositoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i issueLocalRepositoryDo) Debug() IIssueLocalRepositoryDo {
	return i.withDO(i.DO.Debug())
}

func (i issueLocalRepositoryDo) WithContext(ctx context.Context) IIssueLocalRepositoryDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i issueLocalRepositoryDo) ReadDB() IIssueLocalRepositoryDo {
	return i.Clauses(dbresolver.Read)
}

func (i issueLocalRepositoryDo) WriteDB() IIssueLocalRepositoryDo {
	return i.Clauses(dbresolver.Write)
}

func (i issueLocalRepositoryDo) Session(config *gorm.Session) IIssueLocalRepositoryDo {
	return i.withDO(i.DO.Session(config))
}

func (i issueLocalRepositoryDo) Clauses(conds ...clause.Expression) IIssueLocalRepositoryDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i issueLocalRepositoryDo) Returning(value interface{}, columns ...string) IIssueLocalRepositoryDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i issueLocalRepositoryDo) Not(conds ...gen.Condition) IIssueLocalRepositoryDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i issueLocalRepositoryDo) Or(conds ...gen.Condition) IIssueLocalRepositoryDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i issueLocalRepositoryDo) Select(conds ...field.Expr) IIssueLocalRepositoryDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i issueLocalRepositoryDo) Where(conds ...gen.Condition) IIssueLocalRepositoryDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i issueLocalRepositoryDo) Order(conds ...field.Expr) IIssueLocalRepositoryDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i issueLocalRepositoryDo) Distinct(cols ...field.Expr) IIssueLocalRepositoryDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i issueLocalRepositoryDo) Omit(cols ...field.Expr) IIssueLocalRepositoryDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i issueLocalRepositoryDo) Join(table schema.Tabler, on ...field.Expr) IIssueLocalRepositoryDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i issueLocalRepositoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IIssueLocalRepositoryDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i issueLocalRepositoryDo) RightJoin(table schema.Tabler, on ...field.Expr) IIssueLocalRepositoryDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i issueLocalRepositoryDo) Group(cols ...field.Expr) IIssueLocalRepositoryDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i issueLocalRepositoryDo) Having(conds ...gen.Condition) IIssueLocalRepositoryDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i issueLocalRepositoryDo) Limit(limit int) IIssueLocalRepositoryDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i issueLocalRepositoryDo) Offset(offset int) IIssueLocalRepositoryDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i issueLocalRepositoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IIssueLocalRepositoryDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i issueLocalRepositoryDo) Unscoped() IIssueLocalRepositoryDo {
	return i.withDO(i.DO.Unscoped())
}

func (i issueLocalRepositoryDo) Create(values ...*model.IssueLocalRepository) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i issueLocalRepositoryDo) CreateInBatches(values []*model.IssueLocalRepository, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i issueLocalRepositoryDo) Save(values ...*model.IssueLocalRepository) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i issueLocalRepositoryDo) First() (*model.IssueLocalRepository, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.IssueLocalRepository), nil
	}
}

func (i issueLocalRepositoryDo) Take() (*model.IssueLocalRepository, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.IssueLocalRepository), nil
	}
}

func (i issueLocalRepositoryDo) Last() (*model.IssueLocalRepository, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.IssueLocalRepository), nil
	}
}

func (i issueLocalRepositoryDo) Find() ([]*model.IssueLocalRepository, error) {
	result, err := i.DO.Find()
	return result.([]*model.IssueLocalRepository), err
}

func (i issueLocalRepositoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.IssueLocalRepository, err error) {
	buf := make([]*model.IssueLocalRepository, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i issueLocalRepositoryDo) FindInBatches(result *[]*model.IssueLocalRepository, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i issueLocalRepositoryDo) Attrs(attrs ...field.AssignExpr) IIssueLocalRepositoryDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i issueLocalRepositoryDo) Assign(attrs ...field.AssignExpr) IIssueLocalRepositoryDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i issueLocalRepositoryDo) Joins(fields ...field.RelationField) IIssueLocalRepositoryDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i issueLocalRepositoryDo) Preload(fields ...field.RelationField) IIssueLocalRepositoryDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i issueLocalRepositoryDo) FirstOrInit() (*model.IssueLocalRepository, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.IssueLocalRepository), nil
	}
}

func (i issueLocalRepositoryDo) FirstOrCreate() (*model.IssueLocalRepository, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.IssueLocalRepository), nil
	}
}

func (i issueLocalRepositoryDo) FindByPage(offset int, limit int) (result []*model.IssueLocalRepository, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i issueLocalRepositoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i issueLocalRepositoryDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i issueLocalRepositoryDo) Delete(models ...*model.IssueLocalRepository) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *issueLocalRepositoryDo) withDO(do gen.Dao) *issueLocalRepositoryDo {
	i.DO = *do.(*gen.DO)
	return i
}
