// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ocean-harness/src-server/internal/dal/model"
)

func newLocalRepository(db *gorm.DB, opts ...gen.DOOption) localRepository {
	_localRepository := localRepository{}

	_localRepository.localRepositoryDo.UseDB(db, opts...)
	_localRepository.localRepositoryDo.UseModel(&model.LocalRepository{})

	tableName := _localRepository.localRepositoryDo.TableName()
	_localRepository.ALL = field.NewAsterisk(tableName)
	_localRepository.ID = field.NewInt(tableName, "id")
	_localRepository.Name = field.NewString(tableName, "name")
	_localRepository.LocalDir = field.NewString(tableName, "local_dir")
	_localRepository.Description = field.NewString(tableName, "description")
	_localRepository.SubDirList = field.NewString(tableName, "sub_dir_list")
	_localRepository.RemoteURL = field.NewString(tableName, "remote_url")
	_localRepository.CurrentBranch = field.NewString(tableName, "current_branch")
	_localRepository.DefaultBranch = field.NewString(tableName, "default_branch")
	_localRepository.LastCommitAt = field.NewInt(tableName, "last_commit_at")
	_localRepository.LastCommitMessage = field.NewString(tableName, "last_commit_message")
	_localRepository.CreatedAt = field.NewTime(tableName, "created_at")
	_localRepository.UpdatedAt = field.NewTime(tableName, "updated_at")

	_localRepository.fillFieldMap()

	return _localRepository
}

type localRepository struct {
	localRepositoryDo localRepositoryDo

	ALL               field.Asterisk
	ID                field.Int
	Name              field.String
	LocalDir          field.String
	Description       field.String
	SubDirList        field.String
	RemoteURL         field.String
	CurrentBranch     field.String
	DefaultBranch     field.String
	LastCommitAt      field.Int
	LastCommitMessage field.String
	CreatedAt         field.Time
	UpdatedAt         field.Time

	fieldMap map[string]field.Expr
}

func (l localRepository) Table(newTableName string) *localRepository {
	l.localRepositoryDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l localRepository) As(alias string) *localRepository {
	l.localRepositoryDo.DO = *(l.localRepositoryDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *localRepository) updateTableName(table string) *localRepository {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewInt(table, "id")
	l.Name = field.NewString(table, "name")
	l.LocalDir = field.NewString(table, "local_dir")
	l.Description = field.NewString(table, "description")
	l.SubDirList = field.NewString(table, "sub_dir_list")
	l.RemoteURL = field.NewString(table, "remote_url")
	l.CurrentBranch = field.NewString(table, "current_branch")
	l.DefaultBranch = field.NewString(table, "default_branch")
	l.LastCommitAt = field.NewInt(table, "last_commit_at")
	l.LastCommitMessage = field.NewString(table, "last_commit_message")
	l.CreatedAt = field.NewTime(table, "created_at")
	l.UpdatedAt = field.NewTime(table, "updated_at")

	l.fillFieldMap()

	return l
}

func (l *localRepository) WithContext(ctx context.Context) ILocalRepositoryDo {
	return l.localRepositoryDo.WithContext(ctx)
}

func (l localRepository) TableName() string { return l.localRepositoryDo.TableName() }

func (l localRepository) Alias() string { return l.localRepositoryDo.Alias() }

func (l localRepository) Columns(cols ...field.Expr) gen.Columns {
	return l.localRepositoryDo.Columns(cols...)
}

func (l *localRepository) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *localRepository) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 12)
	l.fieldMap["id"] = l.ID
	l.fieldMap["name"] = l.Name
	l.fieldMap["local_dir"] = l.LocalDir
	l.fieldMap["description"] = l.Description
	l.fieldMap["sub_dir_list"] = l.SubDirList
	l.fieldMap["remote_url"] = l.RemoteURL
	l.fieldMap["current_branch"] = l.CurrentBranch
	l.fieldMap["default_branch"] = l.DefaultBranch
	l.fieldMap["last_commit_at"] = l.LastCommitAt
	l.fieldMap["last_commit_message"] = l.LastCommitMessage
	l.fieldMap["created_at"] = l.CreatedAt
	l.fieldMap["updated_at"] = l.UpdatedAt
}

func (l localRepository) clone(db *gorm.DB) localRepository {
	l.localRepositoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l localRepository) replaceDB(db *gorm.DB) localRepository {
	l.localRepositoryDo.ReplaceDB(db)
	return l
}

type localRepositoryDo struct{ gen.DO }

type ILocalRepositoryDo interface {
	gen.SubQuery
	Debug() ILocalRepositoryDo
	WithContext(ctx context.Context) ILocalRepositoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILocalRepositoryDo
	WriteDB() ILocalRepositoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILocalRepositoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILocalRepositoryDo
	Not(conds ...gen.Condition) ILocalRepositoryDo
	Or(conds ...gen.Condition) ILocalRepositoryDo
	Select(conds ...field.Expr) ILocalRepositoryDo
	Where(conds ...gen.Condition) ILocalRepositoryDo
	Order(conds ...field.Expr) ILocalRepositoryDo
	Distinct(cols ...field.Expr) ILocalRepositoryDo
	Omit(cols ...field.Expr) ILocalRepositoryDo
	Join(table schema.Tabler, on ...field.Expr) ILocalRepositoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ILocalRepositoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) ILocalRepositoryDo
	Group(cols ...field.Expr) ILocalRepositoryDo
	Having(conds ...gen.Condition) ILocalRepositoryDo
	Limit(limit int) ILocalRepositoryDo
	Offset(offset int) ILocalRepositoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILocalRepositoryDo
	Unscoped() ILocalRepositoryDo
	Create(values ...*model.LocalRepository) error
	CreateInBatches(values []*model.LocalRepository, batchSize int) error
	Save(values ...*model.LocalRepository) error
	First() (*model.LocalRepository, error)
	Take() (*model.LocalRepository, error)
	Last() (*model.LocalRepository, error)
	Find() ([]*model.LocalRepository, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LocalRepository, err error)
	FindInBatches(result *[]*model.LocalRepository, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.LocalRepository) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILocalRepositoryDo
	Assign(attrs ...field.AssignExpr) ILocalRepositoryDo
	Joins(fields ...field.RelationField) ILocalRepositoryDo
	Preload(fields ...field.RelationField) ILocalRepositoryDo
	FirstOrInit() (*model.LocalRepository, error)
	FirstOrCreate() (*model.LocalRepository, error)
	FindByPage(offset int, limit int) (result []*model.LocalRepository, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILocalRepositoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l localRepositoryDo) Debug() ILocalRepositoryDo {
	return l.withDO(l.DO.Debug())
}

func (l localRepositoryDo) WithContext(ctx context.Context) ILocalRepositoryDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l localRepositoryDo) ReadDB() ILocalRepositoryDo {
	return l.Clauses(dbresolver.Read)
}

func (l localRepositoryDo) WriteDB() ILocalRepositoryDo {
	return l.Clauses(dbresolver.Write)
}

func (l localRepositoryDo) Session(config *gorm.Session) ILocalRepositoryDo {
	return l.withDO(l.DO.Session(config))
}

func (l localRepositoryDo) Clauses(conds ...clause.Expression) ILocalRepositoryDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l localRepositoryDo) Returning(value interface{}, columns ...string) ILocalRepositoryDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l localRepositoryDo) Not(conds ...gen.Condition) ILocalRepositoryDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l localRepositoryDo) Or(conds ...gen.Condition) ILocalRepositoryDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l localRepositoryDo) Select(conds ...field.Expr) ILocalRepositoryDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l localRepositoryDo) Where(conds ...gen.Condition) ILocalRepositoryDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l localRepositoryDo) Order(conds ...field.Expr) ILocalRepositoryDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l localRepositoryDo) Distinct(cols ...field.Expr) ILocalRepositoryDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l localRepositoryDo) Omit(cols ...field.Expr) ILocalRepositoryDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l localRepositoryDo) Join(table schema.Tabler, on ...field.Expr) ILocalRepositoryDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l localRepositoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) ILocalRepositoryDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l localRepositoryDo) RightJoin(table schema.Tabler, on ...field.Expr) ILocalRepositoryDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l localRepositoryDo) Group(cols ...field.Expr) ILocalRepositoryDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l localRepositoryDo) Having(conds ...gen.Condition) ILocalRepositoryDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l localRepositoryDo) Limit(limit int) ILocalRepositoryDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l localRepositoryDo) Offset(offset int) ILocalRepositoryDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l localRepositoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ILocalRepositoryDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l localRepositoryDo) Unscoped() ILocalRepositoryDo {
	return l.withDO(l.DO.Unscoped())
}

func (l localRepositoryDo) Create(values ...*model.LocalRepository) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l localRepositoryDo) CreateInBatches(values []*model.LocalRepository, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l localRepositoryDo) Save(values ...*model.LocalRepository) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l localRepositoryDo) First() (*model.LocalRepository, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LocalRepository), nil
	}
}

func (l localRepositoryDo) Take() (*model.LocalRepository, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LocalRepository), nil
	}
}

func (l localRepositoryDo) Last() (*model.LocalRepository, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LocalRepository), nil
	}
}

func (l localRepositoryDo) Find() ([]*model.LocalRepository, error) {
	result, err := l.DO.Find()
	return result.([]*model.LocalRepository), err
}

func (l localRepositoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LocalRepository, err error) {
	buf := make([]*model.LocalRepository, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l localRepositoryDo) FindInBatches(result *[]*model.LocalRepository, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l localRepositoryDo) Attrs(attrs ...field.AssignExpr) ILocalRepositoryDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l localRepositoryDo) Assign(attrs ...field.AssignExpr) ILocalRepositoryDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l localRepositoryDo) Joins(fields ...field.RelationField) ILocalRepositoryDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l localRepositoryDo) Preload(fields ...field.RelationField) ILocalRepositoryDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l localRepositoryDo) FirstOrInit() (*model.LocalRepository, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LocalRepository), nil
	}
}

func (l localRepositoryDo) FirstOrCreate() (*model.LocalRepository, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LocalRepository), nil
	}
}

func (l localRepositoryDo) FindByPage(offset int, limit int) (result []*model.LocalRepository, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l localRepositoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l localRepositoryDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l localRepositoryDo) Delete(models ...*model.LocalRepository) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *localRepositoryDo) withDO(do gen.Dao) *localRepositoryDo {
	l.DO = *do.(*gen.DO)
	return l
}
