// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"we-claude-terminal/go-server/internal/dal/model"
)

func newProjectState(db *gorm.DB, opts ...gen.DOOption) projectState {
	_projectState := projectState{}

	_projectState.projectStateDo.UseDB(db, opts...)
	_projectState.projectStateDo.UseModel(&model.ProjectState{})

	tableName := _projectState.projectStateDo.TableName()
	_projectState.ALL = field.NewAsterisk(tableName)
	_projectState.ID = field.NewInt(tableName, "id")
	_projectState.ProjectID = field.NewInt(tableName, "project_id")
	_projectState.WorkspaceID = field.NewInt(tableName, "workspace_id")
	_projectState.Name = field.NewString(tableName, "name")
	_projectState.Color = field.NewString(tableName, "color")
	_projectState.Slug = field.NewString(tableName, "slug")
	_projectState.StateGroup = field.NewString(tableName, "state_group")
	_projectState.SortOrder = field.NewFloat64(tableName, "sort_order")
	_projectState.IsDefault = field.NewBool(tableName, "is_default")
	_projectState.IsTriage = field.NewBool(tableName, "is_triage")
	_projectState.CreatedAt = field.NewTime(tableName, "created_at")
	_projectState.UpdatedAt = field.NewTime(tableName, "updated_at")
	_projectState.DeletedAt = field.NewField(tableName, "deleted_at")

	_projectState.fillFieldMap()

	return _projectState
}

type projectState struct {
	projectStateDo projectStateDo

	ALL         field.Asterisk
	ID          field.Int
	ProjectID   field.Int
	WorkspaceID field.Int
	Name        field.String
	Color       field.String
	Slug        field.String
	StateGroup  field.String
	SortOrder   field.Float64
	IsDefault   field.Bool
	IsTriage    field.Bool
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field

	fieldMap map[string]field.Expr
}

func (p projectState) Table(newTableName string) *projectState {
	p.projectStateDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p projectState) As(alias string) *projectState {
	p.projectStateDo.DO = *(p.projectStateDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *projectState) updateTableName(table string) *projectState {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt(table, "id")
	p.ProjectID = field.NewInt(table, "project_id")
	p.WorkspaceID = field.NewInt(table, "workspace_id")
	p.Name = field.NewString(table, "name")
	p.Color = field.NewString(table, "color")
	p.Slug = field.NewString(table, "slug")
	p.StateGroup = field.NewString(table, "state_group")
	p.SortOrder = field.NewFloat64(table, "sort_order")
	p.IsDefault = field.NewBool(table, "is_default")
	p.IsTriage = field.NewBool(table, "is_triage")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewField(table, "deleted_at")

	p.fillFieldMap()

	return p
}

func (p *projectState) WithContext(ctx context.Context) IProjectStateDo {
	return p.projectStateDo.WithContext(ctx)
}

func (p projectState) TableName() string { return p.projectStateDo.TableName() }

func (p projectState) Alias() string { return p.projectStateDo.Alias() }

func (p projectState) Columns(cols ...field.Expr) gen.Columns {
	return p.projectStateDo.Columns(cols...)
}

func (p *projectState) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *projectState) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 13)
	p.fieldMap["id"] = p.ID
	p.fieldMap["project_id"] = p.ProjectID
	p.fieldMap["workspace_id"] = p.WorkspaceID
	p.fieldMap["name"] = p.Name
	p.fieldMap["color"] = p.Color
	p.fieldMap["slug"] = p.Slug
	p.fieldMap["state_group"] = p.StateGroup
	p.fieldMap["sort_order"] = p.SortOrder
	p.fieldMap["is_default"] = p.IsDefault
	p.fieldMap["is_triage"] = p.IsTriage
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
}

func (p projectState) clone(db *gorm.DB) projectState {
	p.projectStateDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p projectState) replaceDB(db *gorm.DB) projectState {
	p.projectStateDo.ReplaceDB(db)
	return p
}

type projectStateDo struct{ gen.DO }

type IProjectStateDo interface {
	gen.SubQuery
	Debug() IProjectStateDo
	WithContext(ctx context.Context) IProjectStateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProjectStateDo
	WriteDB() IProjectStateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProjectStateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProjectStateDo
	Not(conds ...gen.Condition) IProjectStateDo
	Or(conds ...gen.Condition) IProjectStateDo
	Select(conds ...field.Expr) IProjectStateDo
	Where(conds ...gen.Condition) IProjectStateDo
	Order(conds ...field.Expr) IProjectStateDo
	Distinct(cols ...field.Expr) IProjectStateDo
	Omit(cols ...field.Expr) IProjectStateDo
	Join(table schema.Tabler, on ...field.Expr) IProjectStateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProjectStateDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProjectStateDo
	Group(cols ...field.Expr) IProjectStateDo
	Having(conds ...gen.Condition) IProjectStateDo
	Limit(limit int) IProjectStateDo
	Offset(offset int) IProjectStateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProjectStateDo
	Unscoped() IProjectStateDo
	Create(values ...*model.ProjectState) error
	CreateInBatches(values []*model.ProjectState, batchSize int) error
	Save(values ...*model.ProjectState) error
	First() (*model.ProjectState, error)
	Take() (*model.ProjectState, error)
	Last() (*model.ProjectState, error)
	Find() ([]*model.ProjectState, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProjectState, err error)
	FindInBatches(result *[]*model.ProjectState, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ProjectState) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProjectStateDo
	Assign(attrs ...field.AssignExpr) IProjectStateDo
	Joins(fields ...field.RelationField) IProjectStateDo
	Preload(fields ...field.RelationField) IProjectStateDo
	FirstOrInit() (*model.ProjectState, error)
	FirstOrCreate() (*model.ProjectState, error)
	FindByPage(offset int, limit int) (result []*model.ProjectState, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProjectStateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p projectStateDo) Debug() IProjectStateDo {
	return p.withDO(p.DO.Debug())
}

func (p projectStateDo) WithContext(ctx context.Context) IProjectStateDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p projectStateDo) ReadDB() IProjectStateDo {
	return p.Clauses(dbresolver.Read)
}

func (p projectStateDo) WriteDB() IProjectStateDo {
	return p.Clauses(dbresolver.Write)
}

func (p projectStateDo) Session(config *gorm.Session) IProjectStateDo {
	return p.withDO(p.DO.Session(config))
}

func (p projectStateDo) Clauses(conds ...clause.Expression) IProjectStateDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p projectStateDo) Returning(value interface{}, columns ...string) IProjectStateDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p projectStateDo) Not(conds ...gen.Condition) IProjectStateDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p projectStateDo) Or(conds ...gen.Condition) IProjectStateDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p projectStateDo) Select(conds ...field.Expr) IProjectStateDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p projectStateDo) Where(conds ...gen.Condition) IProjectStateDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p projectStateDo) Order(conds ...field.Expr) IProjectStateDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p projectStateDo) Distinct(cols ...field.Expr) IProjectStateDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p projectStateDo) Omit(cols ...field.Expr) IProjectStateDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p projectStateDo) Join(table schema.Tabler, on ...field.Expr) IProjectStateDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p projectStateDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProjectStateDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p projectStateDo) RightJoin(table schema.Tabler, on ...field.Expr) IProjectStateDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p projectStateDo) Group(cols ...field.Expr) IProjectStateDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p projectStateDo) Having(conds ...gen.Condition) IProjectStateDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p projectStateDo) Limit(limit int) IProjectStateDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p projectStateDo) Offset(offset int) IProjectStateDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p projectStateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProjectStateDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p projectStateDo) Unscoped() IProjectStateDo {
	return p.withDO(p.DO.Unscoped())
}

func (p projectStateDo) Create(values ...*model.ProjectState) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p projectStateDo) CreateInBatches(values []*model.ProjectState, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p projectStateDo) Save(values ...*model.ProjectState) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p projectStateDo) First() (*model.ProjectState, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProjectState), nil
	}
}

func (p projectStateDo) Take() (*model.ProjectState, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProjectState), nil
	}
}

func (p projectStateDo) Last() (*model.ProjectState, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProjectState), nil
	}
}

func (p projectStateDo) Find() ([]*model.ProjectState, error) {
	result, err := p.DO.Find()
	return result.([]*model.ProjectState), err
}

func (p projectStateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProjectState, err error) {
	buf := make([]*model.ProjectState, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p projectStateDo) FindInBatches(result *[]*model.ProjectState, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p projectStateDo) Attrs(attrs ...field.AssignExpr) IProjectStateDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p projectStateDo) Assign(attrs ...field.AssignExpr) IProjectStateDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p projectStateDo) Joins(fields ...field.RelationField) IProjectStateDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p projectStateDo) Preload(fields ...field.RelationField) IProjectStateDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p projectStateDo) FirstOrInit() (*model.ProjectState, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProjectState), nil
	}
}

func (p projectStateDo) FirstOrCreate() (*model.ProjectState, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProjectState), nil
	}
}

func (p projectStateDo) FindByPage(offset int, limit int) (result []*model.ProjectState, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p projectStateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p projectStateDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p projectStateDo) Delete(models ...*model.ProjectState) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *projectStateDo) withDO(do gen.Dao) *projectStateDo {
	p.DO = *do.(*gen.DO)
	return p
}
