// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ocean-harness/src-server/internal/dal/model"
)

func newProjectIssue(db *gorm.DB, opts ...gen.DOOption) projectIssue {
	_projectIssue := projectIssue{}

	_projectIssue.projectIssueDo.UseDB(db, opts...)
	_projectIssue.projectIssueDo.UseModel(&model.ProjectIssue{})

	tableName := _projectIssue.projectIssueDo.TableName()
	_projectIssue.ALL = field.NewAsterisk(tableName)
	_projectIssue.ID = field.NewString(tableName, "id")
	_projectIssue.ProjectID = field.NewInt(tableName, "project_id")
	_projectIssue.WorkspaceID = field.NewInt(tableName, "workspace_id")
	_projectIssue.Name = field.NewString(tableName, "name")
	_projectIssue.Description = field.NewString(tableName, "description")
	_projectIssue.StateCode = field.NewField(tableName, "state_code")
	_projectIssue.Priority = field.NewField(tableName, "priority")
	_projectIssue.SortOrder = field.NewFloat64(tableName, "sort_order")
	_projectIssue.ParentID = field.NewString(tableName, "parent_id")
	_projectIssue.StartDate = field.NewString(tableName, "start_date")
	_projectIssue.TargetDate = field.NewString(tableName, "target_date")
	_projectIssue.CompletedAt = field.NewTime(tableName, "completed_at")
	_projectIssue.IsDraft = field.NewField(tableName, "is_draft")
	_projectIssue.CreatedAt = field.NewTime(tableName, "created_at")
	_projectIssue.UpdatedAt = field.NewTime(tableName, "updated_at")
	_projectIssue.IssueLabelList = projectIssueHasManyIssueLabelList{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("IssueLabelList", "model.IssueLabel"),
	}

	_projectIssue.IssueLocalRepositoryList = projectIssueHasManyIssueLocalRepositoryList{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("IssueLocalRepositoryList", "model.IssueLocalRepository"),
	}

	_projectIssue.fillFieldMap()

	return _projectIssue
}

type projectIssue struct {
	projectIssueDo projectIssueDo

	ALL            field.Asterisk
	ID             field.String
	ProjectID      field.Int
	WorkspaceID    field.Int
	Name           field.String
	Description    field.String
	StateCode      field.Field
	Priority       field.Field
	SortOrder      field.Float64
	ParentID       field.String
	StartDate      field.String
	TargetDate     field.String
	CompletedAt    field.Time
	IsDraft        field.Field
	CreatedAt      field.Time
	UpdatedAt      field.Time
	IssueLabelList projectIssueHasManyIssueLabelList

	IssueLocalRepositoryList projectIssueHasManyIssueLocalRepositoryList

	fieldMap map[string]field.Expr
}

func (p projectIssue) Table(newTableName string) *projectIssue {
	p.projectIssueDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p projectIssue) As(alias string) *projectIssue {
	p.projectIssueDo.DO = *(p.projectIssueDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *projectIssue) updateTableName(table string) *projectIssue {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewString(table, "id")
	p.ProjectID = field.NewInt(table, "project_id")
	p.WorkspaceID = field.NewInt(table, "workspace_id")
	p.Name = field.NewString(table, "name")
	p.Description = field.NewString(table, "description")
	p.StateCode = field.NewField(table, "state_code")
	p.Priority = field.NewField(table, "priority")
	p.SortOrder = field.NewFloat64(table, "sort_order")
	p.ParentID = field.NewString(table, "parent_id")
	p.StartDate = field.NewString(table, "start_date")
	p.TargetDate = field.NewString(table, "target_date")
	p.CompletedAt = field.NewTime(table, "completed_at")
	p.IsDraft = field.NewField(table, "is_draft")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")

	p.fillFieldMap()

	return p
}

func (p *projectIssue) WithContext(ctx context.Context) IProjectIssueDo {
	return p.projectIssueDo.WithContext(ctx)
}

func (p projectIssue) TableName() string { return p.projectIssueDo.TableName() }

func (p projectIssue) Alias() string { return p.projectIssueDo.Alias() }

func (p projectIssue) Columns(cols ...field.Expr) gen.Columns {
	return p.projectIssueDo.Columns(cols...)
}

func (p *projectIssue) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *projectIssue) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 17)
	p.fieldMap["id"] = p.ID
	p.fieldMap["project_id"] = p.ProjectID
	p.fieldMap["workspace_id"] = p.WorkspaceID
	p.fieldMap["name"] = p.Name
	p.fieldMap["description"] = p.Description
	p.fieldMap["state_code"] = p.StateCode
	p.fieldMap["priority"] = p.Priority
	p.fieldMap["sort_order"] = p.SortOrder
	p.fieldMap["parent_id"] = p.ParentID
	p.fieldMap["start_date"] = p.StartDate
	p.fieldMap["target_date"] = p.TargetDate
	p.fieldMap["completed_at"] = p.CompletedAt
	p.fieldMap["is_draft"] = p.IsDraft
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt

}

func (p projectIssue) clone(db *gorm.DB) projectIssue {
	p.projectIssueDo.ReplaceConnPool(db.Statement.ConnPool)
	p.IssueLabelList.db = db.Session(&gorm.Session{Initialized: true})
	p.IssueLabelList.db.Statement.ConnPool = db.Statement.ConnPool
	p.IssueLocalRepositoryList.db = db.Session(&gorm.Session{Initialized: true})
	p.IssueLocalRepositoryList.db.Statement.ConnPool = db.Statement.ConnPool
	return p
}

func (p projectIssue) replaceDB(db *gorm.DB) projectIssue {
	p.projectIssueDo.ReplaceDB(db)
	p.IssueLabelList.db = db.Session(&gorm.Session{})
	p.IssueLocalRepositoryList.db = db.Session(&gorm.Session{})
	return p
}

type projectIssueHasManyIssueLabelList struct {
	db *gorm.DB

	field.RelationField
}

func (a projectIssueHasManyIssueLabelList) Where(conds ...field.Expr) *projectIssueHasManyIssueLabelList {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a projectIssueHasManyIssueLabelList) WithContext(ctx context.Context) *projectIssueHasManyIssueLabelList {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a projectIssueHasManyIssueLabelList) Session(session *gorm.Session) *projectIssueHasManyIssueLabelList {
	a.db = a.db.Session(session)
	return &a
}

func (a projectIssueHasManyIssueLabelList) Model(m *model.ProjectIssue) *projectIssueHasManyIssueLabelListTx {
	return &projectIssueHasManyIssueLabelListTx{a.db.Model(m).Association(a.Name())}
}

func (a projectIssueHasManyIssueLabelList) Unscoped() *projectIssueHasManyIssueLabelList {
	a.db = a.db.Unscoped()
	return &a
}

type projectIssueHasManyIssueLabelListTx struct{ tx *gorm.Association }

func (a projectIssueHasManyIssueLabelListTx) Find() (result []*model.IssueLabel, err error) {
	return result, a.tx.Find(&result)
}

func (a projectIssueHasManyIssueLabelListTx) Append(values ...*model.IssueLabel) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a projectIssueHasManyIssueLabelListTx) Replace(values ...*model.IssueLabel) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a projectIssueHasManyIssueLabelListTx) Delete(values ...*model.IssueLabel) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a projectIssueHasManyIssueLabelListTx) Clear() error {
	return a.tx.Clear()
}

func (a projectIssueHasManyIssueLabelListTx) Count() int64 {
	return a.tx.Count()
}

func (a projectIssueHasManyIssueLabelListTx) Unscoped() *projectIssueHasManyIssueLabelListTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type projectIssueHasManyIssueLocalRepositoryList struct {
	db *gorm.DB

	field.RelationField
}

func (a projectIssueHasManyIssueLocalRepositoryList) Where(conds ...field.Expr) *projectIssueHasManyIssueLocalRepositoryList {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a projectIssueHasManyIssueLocalRepositoryList) WithContext(ctx context.Context) *projectIssueHasManyIssueLocalRepositoryList {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a projectIssueHasManyIssueLocalRepositoryList) Session(session *gorm.Session) *projectIssueHasManyIssueLocalRepositoryList {
	a.db = a.db.Session(session)
	return &a
}

func (a projectIssueHasManyIssueLocalRepositoryList) Model(m *model.ProjectIssue) *projectIssueHasManyIssueLocalRepositoryListTx {
	return &projectIssueHasManyIssueLocalRepositoryListTx{a.db.Model(m).Association(a.Name())}
}

func (a projectIssueHasManyIssueLocalRepositoryList) Unscoped() *projectIssueHasManyIssueLocalRepositoryList {
	a.db = a.db.Unscoped()
	return &a
}

type projectIssueHasManyIssueLocalRepositoryListTx struct{ tx *gorm.Association }

func (a projectIssueHasManyIssueLocalRepositoryListTx) Find() (result []*model.IssueLocalRepository, err error) {
	return result, a.tx.Find(&result)
}

func (a projectIssueHasManyIssueLocalRepositoryListTx) Append(values ...*model.IssueLocalRepository) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a projectIssueHasManyIssueLocalRepositoryListTx) Replace(values ...*model.IssueLocalRepository) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a projectIssueHasManyIssueLocalRepositoryListTx) Delete(values ...*model.IssueLocalRepository) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a projectIssueHasManyIssueLocalRepositoryListTx) Clear() error {
	return a.tx.Clear()
}

func (a projectIssueHasManyIssueLocalRepositoryListTx) Count() int64 {
	return a.tx.Count()
}

func (a projectIssueHasManyIssueLocalRepositoryListTx) Unscoped() *projectIssueHasManyIssueLocalRepositoryListTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type projectIssueDo struct{ gen.DO }

type IProjectIssueDo interface {
	gen.SubQuery
	Debug() IProjectIssueDo
	WithContext(ctx context.Context) IProjectIssueDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProjectIssueDo
	WriteDB() IProjectIssueDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProjectIssueDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProjectIssueDo
	Not(conds ...gen.Condition) IProjectIssueDo
	Or(conds ...gen.Condition) IProjectIssueDo
	Select(conds ...field.Expr) IProjectIssueDo
	Where(conds ...gen.Condition) IProjectIssueDo
	Order(conds ...field.Expr) IProjectIssueDo
	Distinct(cols ...field.Expr) IProjectIssueDo
	Omit(cols ...field.Expr) IProjectIssueDo
	Join(table schema.Tabler, on ...field.Expr) IProjectIssueDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProjectIssueDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProjectIssueDo
	Group(cols ...field.Expr) IProjectIssueDo
	Having(conds ...gen.Condition) IProjectIssueDo
	Limit(limit int) IProjectIssueDo
	Offset(offset int) IProjectIssueDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProjectIssueDo
	Unscoped() IProjectIssueDo
	Create(values ...*model.ProjectIssue) error
	CreateInBatches(values []*model.ProjectIssue, batchSize int) error
	Save(values ...*model.ProjectIssue) error
	First() (*model.ProjectIssue, error)
	Take() (*model.ProjectIssue, error)
	Last() (*model.ProjectIssue, error)
	Find() ([]*model.ProjectIssue, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProjectIssue, err error)
	FindInBatches(result *[]*model.ProjectIssue, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ProjectIssue) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProjectIssueDo
	Assign(attrs ...field.AssignExpr) IProjectIssueDo
	Joins(fields ...field.RelationField) IProjectIssueDo
	Preload(fields ...field.RelationField) IProjectIssueDo
	FirstOrInit() (*model.ProjectIssue, error)
	FirstOrCreate() (*model.ProjectIssue, error)
	FindByPage(offset int, limit int) (result []*model.ProjectIssue, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProjectIssueDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p projectIssueDo) Debug() IProjectIssueDo {
	return p.withDO(p.DO.Debug())
}

func (p projectIssueDo) WithContext(ctx context.Context) IProjectIssueDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p projectIssueDo) ReadDB() IProjectIssueDo {
	return p.Clauses(dbresolver.Read)
}

func (p projectIssueDo) WriteDB() IProjectIssueDo {
	return p.Clauses(dbresolver.Write)
}

func (p projectIssueDo) Session(config *gorm.Session) IProjectIssueDo {
	return p.withDO(p.DO.Session(config))
}

func (p projectIssueDo) Clauses(conds ...clause.Expression) IProjectIssueDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p projectIssueDo) Returning(value interface{}, columns ...string) IProjectIssueDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p projectIssueDo) Not(conds ...gen.Condition) IProjectIssueDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p projectIssueDo) Or(conds ...gen.Condition) IProjectIssueDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p projectIssueDo) Select(conds ...field.Expr) IProjectIssueDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p projectIssueDo) Where(conds ...gen.Condition) IProjectIssueDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p projectIssueDo) Order(conds ...field.Expr) IProjectIssueDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p projectIssueDo) Distinct(cols ...field.Expr) IProjectIssueDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p projectIssueDo) Omit(cols ...field.Expr) IProjectIssueDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p projectIssueDo) Join(table schema.Tabler, on ...field.Expr) IProjectIssueDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p projectIssueDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProjectIssueDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p projectIssueDo) RightJoin(table schema.Tabler, on ...field.Expr) IProjectIssueDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p projectIssueDo) Group(cols ...field.Expr) IProjectIssueDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p projectIssueDo) Having(conds ...gen.Condition) IProjectIssueDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p projectIssueDo) Limit(limit int) IProjectIssueDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p projectIssueDo) Offset(offset int) IProjectIssueDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p projectIssueDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProjectIssueDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p projectIssueDo) Unscoped() IProjectIssueDo {
	return p.withDO(p.DO.Unscoped())
}

func (p projectIssueDo) Create(values ...*model.ProjectIssue) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p projectIssueDo) CreateInBatches(values []*model.ProjectIssue, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p projectIssueDo) Save(values ...*model.ProjectIssue) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p projectIssueDo) First() (*model.ProjectIssue, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProjectIssue), nil
	}
}

func (p projectIssueDo) Take() (*model.ProjectIssue, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProjectIssue), nil
	}
}

func (p projectIssueDo) Last() (*model.ProjectIssue, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProjectIssue), nil
	}
}

func (p projectIssueDo) Find() ([]*model.ProjectIssue, error) {
	result, err := p.DO.Find()
	return result.([]*model.ProjectIssue), err
}

func (p projectIssueDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProjectIssue, err error) {
	buf := make([]*model.ProjectIssue, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p projectIssueDo) FindInBatches(result *[]*model.ProjectIssue, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p projectIssueDo) Attrs(attrs ...field.AssignExpr) IProjectIssueDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p projectIssueDo) Assign(attrs ...field.AssignExpr) IProjectIssueDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p projectIssueDo) Joins(fields ...field.RelationField) IProjectIssueDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p projectIssueDo) Preload(fields ...field.RelationField) IProjectIssueDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p projectIssueDo) FirstOrInit() (*model.ProjectIssue, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProjectIssue), nil
	}
}

func (p projectIssueDo) FirstOrCreate() (*model.ProjectIssue, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProjectIssue), nil
	}
}

func (p projectIssueDo) FindByPage(offset int, limit int) (result []*model.ProjectIssue, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p projectIssueDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p projectIssueDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p projectIssueDo) Delete(models ...*model.ProjectIssue) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *projectIssueDo) withDO(do gen.Dao) *projectIssueDo {
	p.DO = *do.(*gen.DO)
	return p
}
