// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ocean-harness/src-server/internal/dal/model"
)

func newProjectLocalRepository(db *gorm.DB, opts ...gen.DOOption) projectLocalRepository {
	_projectLocalRepository := projectLocalRepository{}

	_projectLocalRepository.projectLocalRepositoryDo.UseDB(db, opts...)
	_projectLocalRepository.projectLocalRepositoryDo.UseModel(&model.ProjectLocalRepository{})

	tableName := _projectLocalRepository.projectLocalRepositoryDo.TableName()
	_projectLocalRepository.ALL = field.NewAsterisk(tableName)
	_projectLocalRepository.ID = field.NewInt(tableName, "id")
	_projectLocalRepository.WorkspaceProjectID = field.NewInt(tableName, "workspace_project_id")
	_projectLocalRepository.LocalRepositoryID = field.NewInt(tableName, "local_repository_id")
	_projectLocalRepository.CreatedAt = field.NewTime(tableName, "created_at")
	_projectLocalRepository.UpdatedAt = field.NewTime(tableName, "updated_at")

	_projectLocalRepository.fillFieldMap()

	return _projectLocalRepository
}

type projectLocalRepository struct {
	projectLocalRepositoryDo projectLocalRepositoryDo

	ALL                field.Asterisk
	ID                 field.Int
	WorkspaceProjectID field.Int
	LocalRepositoryID  field.Int
	CreatedAt          field.Time
	UpdatedAt          field.Time

	fieldMap map[string]field.Expr
}

func (p projectLocalRepository) Table(newTableName string) *projectLocalRepository {
	p.projectLocalRepositoryDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p projectLocalRepository) As(alias string) *projectLocalRepository {
	p.projectLocalRepositoryDo.DO = *(p.projectLocalRepositoryDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *projectLocalRepository) updateTableName(table string) *projectLocalRepository {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt(table, "id")
	p.WorkspaceProjectID = field.NewInt(table, "workspace_project_id")
	p.LocalRepositoryID = field.NewInt(table, "local_repository_id")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")

	p.fillFieldMap()

	return p
}

func (p *projectLocalRepository) WithContext(ctx context.Context) IProjectLocalRepositoryDo {
	return p.projectLocalRepositoryDo.WithContext(ctx)
}

func (p projectLocalRepository) TableName() string { return p.projectLocalRepositoryDo.TableName() }

func (p projectLocalRepository) Alias() string { return p.projectLocalRepositoryDo.Alias() }

func (p projectLocalRepository) Columns(cols ...field.Expr) gen.Columns {
	return p.projectLocalRepositoryDo.Columns(cols...)
}

func (p *projectLocalRepository) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *projectLocalRepository) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 5)
	p.fieldMap["id"] = p.ID
	p.fieldMap["workspace_project_id"] = p.WorkspaceProjectID
	p.fieldMap["local_repository_id"] = p.LocalRepositoryID
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
}

func (p projectLocalRepository) clone(db *gorm.DB) projectLocalRepository {
	p.projectLocalRepositoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p projectLocalRepository) replaceDB(db *gorm.DB) projectLocalRepository {
	p.projectLocalRepositoryDo.ReplaceDB(db)
	return p
}

type projectLocalRepositoryDo struct{ gen.DO }

type IProjectLocalRepositoryDo interface {
	gen.SubQuery
	Debug() IProjectLocalRepositoryDo
	WithContext(ctx context.Context) IProjectLocalRepositoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProjectLocalRepositoryDo
	WriteDB() IProjectLocalRepositoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProjectLocalRepositoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProjectLocalRepositoryDo
	Not(conds ...gen.Condition) IProjectLocalRepositoryDo
	Or(conds ...gen.Condition) IProjectLocalRepositoryDo
	Select(conds ...field.Expr) IProjectLocalRepositoryDo
	Where(conds ...gen.Condition) IProjectLocalRepositoryDo
	Order(conds ...field.Expr) IProjectLocalRepositoryDo
	Distinct(cols ...field.Expr) IProjectLocalRepositoryDo
	Omit(cols ...field.Expr) IProjectLocalRepositoryDo
	Join(table schema.Tabler, on ...field.Expr) IProjectLocalRepositoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProjectLocalRepositoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProjectLocalRepositoryDo
	Group(cols ...field.Expr) IProjectLocalRepositoryDo
	Having(conds ...gen.Condition) IProjectLocalRepositoryDo
	Limit(limit int) IProjectLocalRepositoryDo
	Offset(offset int) IProjectLocalRepositoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProjectLocalRepositoryDo
	Unscoped() IProjectLocalRepositoryDo
	Create(values ...*model.ProjectLocalRepository) error
	CreateInBatches(values []*model.ProjectLocalRepository, batchSize int) error
	Save(values ...*model.ProjectLocalRepository) error
	First() (*model.ProjectLocalRepository, error)
	Take() (*model.ProjectLocalRepository, error)
	Last() (*model.ProjectLocalRepository, error)
	Find() ([]*model.ProjectLocalRepository, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProjectLocalRepository, err error)
	FindInBatches(result *[]*model.ProjectLocalRepository, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ProjectLocalRepository) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProjectLocalRepositoryDo
	Assign(attrs ...field.AssignExpr) IProjectLocalRepositoryDo
	Joins(fields ...field.RelationField) IProjectLocalRepositoryDo
	Preload(fields ...field.RelationField) IProjectLocalRepositoryDo
	FirstOrInit() (*model.ProjectLocalRepository, error)
	FirstOrCreate() (*model.ProjectLocalRepository, error)
	FindByPage(offset int, limit int) (result []*model.ProjectLocalRepository, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProjectLocalRepositoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p projectLocalRepositoryDo) Debug() IProjectLocalRepositoryDo {
	return p.withDO(p.DO.Debug())
}

func (p projectLocalRepositoryDo) WithContext(ctx context.Context) IProjectLocalRepositoryDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p projectLocalRepositoryDo) ReadDB() IProjectLocalRepositoryDo {
	return p.Clauses(dbresolver.Read)
}

func (p projectLocalRepositoryDo) WriteDB() IProjectLocalRepositoryDo {
	return p.Clauses(dbresolver.Write)
}

func (p projectLocalRepositoryDo) Session(config *gorm.Session) IProjectLocalRepositoryDo {
	return p.withDO(p.DO.Session(config))
}

func (p projectLocalRepositoryDo) Clauses(conds ...clause.Expression) IProjectLocalRepositoryDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p projectLocalRepositoryDo) Returning(value interface{}, columns ...string) IProjectLocalRepositoryDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p projectLocalRepositoryDo) Not(conds ...gen.Condition) IProjectLocalRepositoryDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p projectLocalRepositoryDo) Or(conds ...gen.Condition) IProjectLocalRepositoryDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p projectLocalRepositoryDo) Select(conds ...field.Expr) IProjectLocalRepositoryDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p projectLocalRepositoryDo) Where(conds ...gen.Condition) IProjectLocalRepositoryDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p projectLocalRepositoryDo) Order(conds ...field.Expr) IProjectLocalRepositoryDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p projectLocalRepositoryDo) Distinct(cols ...field.Expr) IProjectLocalRepositoryDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p projectLocalRepositoryDo) Omit(cols ...field.Expr) IProjectLocalRepositoryDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p projectLocalRepositoryDo) Join(table schema.Tabler, on ...field.Expr) IProjectLocalRepositoryDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p projectLocalRepositoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProjectLocalRepositoryDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p projectLocalRepositoryDo) RightJoin(table schema.Tabler, on ...field.Expr) IProjectLocalRepositoryDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p projectLocalRepositoryDo) Group(cols ...field.Expr) IProjectLocalRepositoryDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p projectLocalRepositoryDo) Having(conds ...gen.Condition) IProjectLocalRepositoryDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p projectLocalRepositoryDo) Limit(limit int) IProjectLocalRepositoryDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p projectLocalRepositoryDo) Offset(offset int) IProjectLocalRepositoryDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p projectLocalRepositoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProjectLocalRepositoryDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p projectLocalRepositoryDo) Unscoped() IProjectLocalRepositoryDo {
	return p.withDO(p.DO.Unscoped())
}

func (p projectLocalRepositoryDo) Create(values ...*model.ProjectLocalRepository) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p projectLocalRepositoryDo) CreateInBatches(values []*model.ProjectLocalRepository, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p projectLocalRepositoryDo) Save(values ...*model.ProjectLocalRepository) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p projectLocalRepositoryDo) First() (*model.ProjectLocalRepository, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProjectLocalRepository), nil
	}
}

func (p projectLocalRepositoryDo) Take() (*model.ProjectLocalRepository, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProjectLocalRepository), nil
	}
}

func (p projectLocalRepositoryDo) Last() (*model.ProjectLocalRepository, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProjectLocalRepository), nil
	}
}

func (p projectLocalRepositoryDo) Find() ([]*model.ProjectLocalRepository, error) {
	result, err := p.DO.Find()
	return result.([]*model.ProjectLocalRepository), err
}

func (p projectLocalRepositoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProjectLocalRepository, err error) {
	buf := make([]*model.ProjectLocalRepository, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p projectLocalRepositoryDo) FindInBatches(result *[]*model.ProjectLocalRepository, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p projectLocalRepositoryDo) Attrs(attrs ...field.AssignExpr) IProjectLocalRepositoryDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p projectLocalRepositoryDo) Assign(attrs ...field.AssignExpr) IProjectLocalRepositoryDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p projectLocalRepositoryDo) Joins(fields ...field.RelationField) IProjectLocalRepositoryDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p projectLocalRepositoryDo) Preload(fields ...field.RelationField) IProjectLocalRepositoryDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p projectLocalRepositoryDo) FirstOrInit() (*model.ProjectLocalRepository, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProjectLocalRepository), nil
	}
}

func (p projectLocalRepositoryDo) FirstOrCreate() (*model.ProjectLocalRepository, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProjectLocalRepository), nil
	}
}

func (p projectLocalRepositoryDo) FindByPage(offset int, limit int) (result []*model.ProjectLocalRepository, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p projectLocalRepositoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p projectLocalRepositoryDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p projectLocalRepositoryDo) Delete(models ...*model.ProjectLocalRepository) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *projectLocalRepositoryDo) withDO(do gen.Dao) *projectLocalRepositoryDo {
	p.DO = *do.(*gen.DO)
	return p
}
