// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"we-claude-terminal/go-server/internal/dal/model"
)

func newWorkspaceProject(db *gorm.DB, opts ...gen.DOOption) workspaceProject {
	_workspaceProject := workspaceProject{}

	_workspaceProject.workspaceProjectDo.UseDB(db, opts...)
	_workspaceProject.workspaceProjectDo.UseModel(&model.WorkspaceProject{})

	tableName := _workspaceProject.workspaceProjectDo.TableName()
	_workspaceProject.ALL = field.NewAsterisk(tableName)
	_workspaceProject.ID = field.NewInt(tableName, "id")
	_workspaceProject.WorkspaceID = field.NewInt(tableName, "workspace_id")
	_workspaceProject.Name = field.NewString(tableName, "name")
	_workspaceProject.Description = field.NewString(tableName, "description")
	_workspaceProject.Emoji = field.NewString(tableName, "emoji")
	_workspaceProject.CreatedAt = field.NewTime(tableName, "created_at")
	_workspaceProject.UpdatedAt = field.NewTime(tableName, "updated_at")
	_workspaceProject.DeletedAt = field.NewField(tableName, "deleted_at")
	_workspaceProject.ProjectIssueList = workspaceProjectHasManyProjectIssueList{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("ProjectIssueList", "model.ProjectIssue"),
		IssueLabelList: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("ProjectIssueList.IssueLabelList", "model.IssueLabel"),
		},
	}

	_workspaceProject.ProjectLocalRepositoryList = workspaceProjectHasManyProjectLocalRepositoryList{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("ProjectLocalRepositoryList", "model.ProjectLocalRepository"),
	}

	_workspaceProject.fillFieldMap()

	return _workspaceProject
}

type workspaceProject struct {
	workspaceProjectDo workspaceProjectDo

	ALL              field.Asterisk
	ID               field.Int
	WorkspaceID      field.Int
	Name             field.String
	Description      field.String
	Emoji            field.String
	CreatedAt        field.Time
	UpdatedAt        field.Time
	DeletedAt        field.Field
	ProjectIssueList workspaceProjectHasManyProjectIssueList

	ProjectLocalRepositoryList workspaceProjectHasManyProjectLocalRepositoryList

	fieldMap map[string]field.Expr
}

func (w workspaceProject) Table(newTableName string) *workspaceProject {
	w.workspaceProjectDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w workspaceProject) As(alias string) *workspaceProject {
	w.workspaceProjectDo.DO = *(w.workspaceProjectDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *workspaceProject) updateTableName(table string) *workspaceProject {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewInt(table, "id")
	w.WorkspaceID = field.NewInt(table, "workspace_id")
	w.Name = field.NewString(table, "name")
	w.Description = field.NewString(table, "description")
	w.Emoji = field.NewString(table, "emoji")
	w.CreatedAt = field.NewTime(table, "created_at")
	w.UpdatedAt = field.NewTime(table, "updated_at")
	w.DeletedAt = field.NewField(table, "deleted_at")

	w.fillFieldMap()

	return w
}

func (w *workspaceProject) WithContext(ctx context.Context) IWorkspaceProjectDo {
	return w.workspaceProjectDo.WithContext(ctx)
}

func (w workspaceProject) TableName() string { return w.workspaceProjectDo.TableName() }

func (w workspaceProject) Alias() string { return w.workspaceProjectDo.Alias() }

func (w workspaceProject) Columns(cols ...field.Expr) gen.Columns {
	return w.workspaceProjectDo.Columns(cols...)
}

func (w *workspaceProject) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *workspaceProject) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 10)
	w.fieldMap["id"] = w.ID
	w.fieldMap["workspace_id"] = w.WorkspaceID
	w.fieldMap["name"] = w.Name
	w.fieldMap["description"] = w.Description
	w.fieldMap["emoji"] = w.Emoji
	w.fieldMap["created_at"] = w.CreatedAt
	w.fieldMap["updated_at"] = w.UpdatedAt
	w.fieldMap["deleted_at"] = w.DeletedAt

}

func (w workspaceProject) clone(db *gorm.DB) workspaceProject {
	w.workspaceProjectDo.ReplaceConnPool(db.Statement.ConnPool)
	w.ProjectIssueList.db = db.Session(&gorm.Session{Initialized: true})
	w.ProjectIssueList.db.Statement.ConnPool = db.Statement.ConnPool
	w.ProjectLocalRepositoryList.db = db.Session(&gorm.Session{Initialized: true})
	w.ProjectLocalRepositoryList.db.Statement.ConnPool = db.Statement.ConnPool
	return w
}

func (w workspaceProject) replaceDB(db *gorm.DB) workspaceProject {
	w.workspaceProjectDo.ReplaceDB(db)
	w.ProjectIssueList.db = db.Session(&gorm.Session{})
	w.ProjectLocalRepositoryList.db = db.Session(&gorm.Session{})
	return w
}

type workspaceProjectHasManyProjectIssueList struct {
	db *gorm.DB

	field.RelationField

	IssueLabelList struct {
		field.RelationField
	}
}

func (a workspaceProjectHasManyProjectIssueList) Where(conds ...field.Expr) *workspaceProjectHasManyProjectIssueList {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a workspaceProjectHasManyProjectIssueList) WithContext(ctx context.Context) *workspaceProjectHasManyProjectIssueList {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a workspaceProjectHasManyProjectIssueList) Session(session *gorm.Session) *workspaceProjectHasManyProjectIssueList {
	a.db = a.db.Session(session)
	return &a
}

func (a workspaceProjectHasManyProjectIssueList) Model(m *model.WorkspaceProject) *workspaceProjectHasManyProjectIssueListTx {
	return &workspaceProjectHasManyProjectIssueListTx{a.db.Model(m).Association(a.Name())}
}

func (a workspaceProjectHasManyProjectIssueList) Unscoped() *workspaceProjectHasManyProjectIssueList {
	a.db = a.db.Unscoped()
	return &a
}

type workspaceProjectHasManyProjectIssueListTx struct{ tx *gorm.Association }

func (a workspaceProjectHasManyProjectIssueListTx) Find() (result []*model.ProjectIssue, err error) {
	return result, a.tx.Find(&result)
}

func (a workspaceProjectHasManyProjectIssueListTx) Append(values ...*model.ProjectIssue) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a workspaceProjectHasManyProjectIssueListTx) Replace(values ...*model.ProjectIssue) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a workspaceProjectHasManyProjectIssueListTx) Delete(values ...*model.ProjectIssue) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a workspaceProjectHasManyProjectIssueListTx) Clear() error {
	return a.tx.Clear()
}

func (a workspaceProjectHasManyProjectIssueListTx) Count() int64 {
	return a.tx.Count()
}

func (a workspaceProjectHasManyProjectIssueListTx) Unscoped() *workspaceProjectHasManyProjectIssueListTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type workspaceProjectHasManyProjectLocalRepositoryList struct {
	db *gorm.DB

	field.RelationField
}

func (a workspaceProjectHasManyProjectLocalRepositoryList) Where(conds ...field.Expr) *workspaceProjectHasManyProjectLocalRepositoryList {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a workspaceProjectHasManyProjectLocalRepositoryList) WithContext(ctx context.Context) *workspaceProjectHasManyProjectLocalRepositoryList {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a workspaceProjectHasManyProjectLocalRepositoryList) Session(session *gorm.Session) *workspaceProjectHasManyProjectLocalRepositoryList {
	a.db = a.db.Session(session)
	return &a
}

func (a workspaceProjectHasManyProjectLocalRepositoryList) Model(m *model.WorkspaceProject) *workspaceProjectHasManyProjectLocalRepositoryListTx {
	return &workspaceProjectHasManyProjectLocalRepositoryListTx{a.db.Model(m).Association(a.Name())}
}

func (a workspaceProjectHasManyProjectLocalRepositoryList) Unscoped() *workspaceProjectHasManyProjectLocalRepositoryList {
	a.db = a.db.Unscoped()
	return &a
}

type workspaceProjectHasManyProjectLocalRepositoryListTx struct{ tx *gorm.Association }

func (a workspaceProjectHasManyProjectLocalRepositoryListTx) Find() (result []*model.ProjectLocalRepository, err error) {
	return result, a.tx.Find(&result)
}

func (a workspaceProjectHasManyProjectLocalRepositoryListTx) Append(values ...*model.ProjectLocalRepository) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a workspaceProjectHasManyProjectLocalRepositoryListTx) Replace(values ...*model.ProjectLocalRepository) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a workspaceProjectHasManyProjectLocalRepositoryListTx) Delete(values ...*model.ProjectLocalRepository) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a workspaceProjectHasManyProjectLocalRepositoryListTx) Clear() error {
	return a.tx.Clear()
}

func (a workspaceProjectHasManyProjectLocalRepositoryListTx) Count() int64 {
	return a.tx.Count()
}

func (a workspaceProjectHasManyProjectLocalRepositoryListTx) Unscoped() *workspaceProjectHasManyProjectLocalRepositoryListTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type workspaceProjectDo struct{ gen.DO }

type IWorkspaceProjectDo interface {
	gen.SubQuery
	Debug() IWorkspaceProjectDo
	WithContext(ctx context.Context) IWorkspaceProjectDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWorkspaceProjectDo
	WriteDB() IWorkspaceProjectDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWorkspaceProjectDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWorkspaceProjectDo
	Not(conds ...gen.Condition) IWorkspaceProjectDo
	Or(conds ...gen.Condition) IWorkspaceProjectDo
	Select(conds ...field.Expr) IWorkspaceProjectDo
	Where(conds ...gen.Condition) IWorkspaceProjectDo
	Order(conds ...field.Expr) IWorkspaceProjectDo
	Distinct(cols ...field.Expr) IWorkspaceProjectDo
	Omit(cols ...field.Expr) IWorkspaceProjectDo
	Join(table schema.Tabler, on ...field.Expr) IWorkspaceProjectDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWorkspaceProjectDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWorkspaceProjectDo
	Group(cols ...field.Expr) IWorkspaceProjectDo
	Having(conds ...gen.Condition) IWorkspaceProjectDo
	Limit(limit int) IWorkspaceProjectDo
	Offset(offset int) IWorkspaceProjectDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWorkspaceProjectDo
	Unscoped() IWorkspaceProjectDo
	Create(values ...*model.WorkspaceProject) error
	CreateInBatches(values []*model.WorkspaceProject, batchSize int) error
	Save(values ...*model.WorkspaceProject) error
	First() (*model.WorkspaceProject, error)
	Take() (*model.WorkspaceProject, error)
	Last() (*model.WorkspaceProject, error)
	Find() ([]*model.WorkspaceProject, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WorkspaceProject, err error)
	FindInBatches(result *[]*model.WorkspaceProject, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.WorkspaceProject) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWorkspaceProjectDo
	Assign(attrs ...field.AssignExpr) IWorkspaceProjectDo
	Joins(fields ...field.RelationField) IWorkspaceProjectDo
	Preload(fields ...field.RelationField) IWorkspaceProjectDo
	FirstOrInit() (*model.WorkspaceProject, error)
	FirstOrCreate() (*model.WorkspaceProject, error)
	FindByPage(offset int, limit int) (result []*model.WorkspaceProject, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWorkspaceProjectDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w workspaceProjectDo) Debug() IWorkspaceProjectDo {
	return w.withDO(w.DO.Debug())
}

func (w workspaceProjectDo) WithContext(ctx context.Context) IWorkspaceProjectDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w workspaceProjectDo) ReadDB() IWorkspaceProjectDo {
	return w.Clauses(dbresolver.Read)
}

func (w workspaceProjectDo) WriteDB() IWorkspaceProjectDo {
	return w.Clauses(dbresolver.Write)
}

func (w workspaceProjectDo) Session(config *gorm.Session) IWorkspaceProjectDo {
	return w.withDO(w.DO.Session(config))
}

func (w workspaceProjectDo) Clauses(conds ...clause.Expression) IWorkspaceProjectDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w workspaceProjectDo) Returning(value interface{}, columns ...string) IWorkspaceProjectDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w workspaceProjectDo) Not(conds ...gen.Condition) IWorkspaceProjectDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w workspaceProjectDo) Or(conds ...gen.Condition) IWorkspaceProjectDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w workspaceProjectDo) Select(conds ...field.Expr) IWorkspaceProjectDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w workspaceProjectDo) Where(conds ...gen.Condition) IWorkspaceProjectDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w workspaceProjectDo) Order(conds ...field.Expr) IWorkspaceProjectDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w workspaceProjectDo) Distinct(cols ...field.Expr) IWorkspaceProjectDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w workspaceProjectDo) Omit(cols ...field.Expr) IWorkspaceProjectDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w workspaceProjectDo) Join(table schema.Tabler, on ...field.Expr) IWorkspaceProjectDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w workspaceProjectDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWorkspaceProjectDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w workspaceProjectDo) RightJoin(table schema.Tabler, on ...field.Expr) IWorkspaceProjectDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w workspaceProjectDo) Group(cols ...field.Expr) IWorkspaceProjectDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w workspaceProjectDo) Having(conds ...gen.Condition) IWorkspaceProjectDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w workspaceProjectDo) Limit(limit int) IWorkspaceProjectDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w workspaceProjectDo) Offset(offset int) IWorkspaceProjectDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w workspaceProjectDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWorkspaceProjectDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w workspaceProjectDo) Unscoped() IWorkspaceProjectDo {
	return w.withDO(w.DO.Unscoped())
}

func (w workspaceProjectDo) Create(values ...*model.WorkspaceProject) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w workspaceProjectDo) CreateInBatches(values []*model.WorkspaceProject, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w workspaceProjectDo) Save(values ...*model.WorkspaceProject) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w workspaceProjectDo) First() (*model.WorkspaceProject, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkspaceProject), nil
	}
}

func (w workspaceProjectDo) Take() (*model.WorkspaceProject, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkspaceProject), nil
	}
}

func (w workspaceProjectDo) Last() (*model.WorkspaceProject, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkspaceProject), nil
	}
}

func (w workspaceProjectDo) Find() ([]*model.WorkspaceProject, error) {
	result, err := w.DO.Find()
	return result.([]*model.WorkspaceProject), err
}

func (w workspaceProjectDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WorkspaceProject, err error) {
	buf := make([]*model.WorkspaceProject, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w workspaceProjectDo) FindInBatches(result *[]*model.WorkspaceProject, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w workspaceProjectDo) Attrs(attrs ...field.AssignExpr) IWorkspaceProjectDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w workspaceProjectDo) Assign(attrs ...field.AssignExpr) IWorkspaceProjectDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w workspaceProjectDo) Joins(fields ...field.RelationField) IWorkspaceProjectDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w workspaceProjectDo) Preload(fields ...field.RelationField) IWorkspaceProjectDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w workspaceProjectDo) FirstOrInit() (*model.WorkspaceProject, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkspaceProject), nil
	}
}

func (w workspaceProjectDo) FirstOrCreate() (*model.WorkspaceProject, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkspaceProject), nil
	}
}

func (w workspaceProjectDo) FindByPage(offset int, limit int) (result []*model.WorkspaceProject, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w workspaceProjectDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w workspaceProjectDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w workspaceProjectDo) Delete(models ...*model.WorkspaceProject) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *workspaceProjectDo) withDO(do gen.Dao) *workspaceProjectDo {
	w.DO = *do.(*gen.DO)
	return w
}
