// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"we-claude-terminal/go-server/internal/dal/model"
)

func newWorkspace(db *gorm.DB, opts ...gen.DOOption) workspace {
	_workspace := workspace{}

	_workspace.workspaceDo.UseDB(db, opts...)
	_workspace.workspaceDo.UseModel(&model.Workspace{})

	tableName := _workspace.workspaceDo.TableName()
	_workspace.ALL = field.NewAsterisk(tableName)
	_workspace.ID = field.NewInt(tableName, "id")
	_workspace.Name = field.NewString(tableName, "name")
	_workspace.Slug = field.NewString(tableName, "slug")
	_workspace.Description = field.NewString(tableName, "description")
	_workspace.WorktreeRoot = field.NewString(tableName, "worktree_root")
	_workspace.CreatedAt = field.NewTime(tableName, "created_at")
	_workspace.UpdatedAt = field.NewTime(tableName, "updated_at")
	_workspace.DeletedAt = field.NewField(tableName, "deleted_at")
	_workspace.WorkspaceProjectList = workspaceHasManyWorkspaceProjectList{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("WorkspaceProjectList", "model.WorkspaceProject"),
		ProjectIssueList: struct {
			field.RelationField
			IssueLabelList struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("WorkspaceProjectList.ProjectIssueList", "model.ProjectIssue"),
			IssueLabelList: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("WorkspaceProjectList.ProjectIssueList.IssueLabelList", "model.IssueLabel"),
			},
		},
		ProjectLocalRepositoryList: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("WorkspaceProjectList.ProjectLocalRepositoryList", "model.ProjectLocalRepository"),
		},
	}

	_workspace.WorkspaceLabelList = workspaceHasManyWorkspaceLabelList{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("WorkspaceLabelList", "model.WorkspaceLabel"),
	}

	_workspace.fillFieldMap()

	return _workspace
}

type workspace struct {
	workspaceDo workspaceDo

	ALL                  field.Asterisk
	ID                   field.Int
	Name                 field.String
	Slug                 field.String
	Description          field.String
	WorktreeRoot         field.String
	CreatedAt            field.Time
	UpdatedAt            field.Time
	DeletedAt            field.Field
	WorkspaceProjectList workspaceHasManyWorkspaceProjectList

	WorkspaceLabelList workspaceHasManyWorkspaceLabelList

	fieldMap map[string]field.Expr
}

func (w workspace) Table(newTableName string) *workspace {
	w.workspaceDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w workspace) As(alias string) *workspace {
	w.workspaceDo.DO = *(w.workspaceDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *workspace) updateTableName(table string) *workspace {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewInt(table, "id")
	w.Name = field.NewString(table, "name")
	w.Slug = field.NewString(table, "slug")
	w.Description = field.NewString(table, "description")
	w.WorktreeRoot = field.NewString(table, "worktree_root")
	w.CreatedAt = field.NewTime(table, "created_at")
	w.UpdatedAt = field.NewTime(table, "updated_at")
	w.DeletedAt = field.NewField(table, "deleted_at")

	w.fillFieldMap()

	return w
}

func (w *workspace) WithContext(ctx context.Context) IWorkspaceDo {
	return w.workspaceDo.WithContext(ctx)
}

func (w workspace) TableName() string { return w.workspaceDo.TableName() }

func (w workspace) Alias() string { return w.workspaceDo.Alias() }

func (w workspace) Columns(cols ...field.Expr) gen.Columns { return w.workspaceDo.Columns(cols...) }

func (w *workspace) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *workspace) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 10)
	w.fieldMap["id"] = w.ID
	w.fieldMap["name"] = w.Name
	w.fieldMap["slug"] = w.Slug
	w.fieldMap["description"] = w.Description
	w.fieldMap["worktree_root"] = w.WorktreeRoot
	w.fieldMap["created_at"] = w.CreatedAt
	w.fieldMap["updated_at"] = w.UpdatedAt
	w.fieldMap["deleted_at"] = w.DeletedAt

}

func (w workspace) clone(db *gorm.DB) workspace {
	w.workspaceDo.ReplaceConnPool(db.Statement.ConnPool)
	w.WorkspaceProjectList.db = db.Session(&gorm.Session{Initialized: true})
	w.WorkspaceProjectList.db.Statement.ConnPool = db.Statement.ConnPool
	w.WorkspaceLabelList.db = db.Session(&gorm.Session{Initialized: true})
	w.WorkspaceLabelList.db.Statement.ConnPool = db.Statement.ConnPool
	return w
}

func (w workspace) replaceDB(db *gorm.DB) workspace {
	w.workspaceDo.ReplaceDB(db)
	w.WorkspaceProjectList.db = db.Session(&gorm.Session{})
	w.WorkspaceLabelList.db = db.Session(&gorm.Session{})
	return w
}

type workspaceHasManyWorkspaceProjectList struct {
	db *gorm.DB

	field.RelationField

	ProjectIssueList struct {
		field.RelationField
		IssueLabelList struct {
			field.RelationField
		}
	}
	ProjectLocalRepositoryList struct {
		field.RelationField
	}
}

func (a workspaceHasManyWorkspaceProjectList) Where(conds ...field.Expr) *workspaceHasManyWorkspaceProjectList {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a workspaceHasManyWorkspaceProjectList) WithContext(ctx context.Context) *workspaceHasManyWorkspaceProjectList {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a workspaceHasManyWorkspaceProjectList) Session(session *gorm.Session) *workspaceHasManyWorkspaceProjectList {
	a.db = a.db.Session(session)
	return &a
}

func (a workspaceHasManyWorkspaceProjectList) Model(m *model.Workspace) *workspaceHasManyWorkspaceProjectListTx {
	return &workspaceHasManyWorkspaceProjectListTx{a.db.Model(m).Association(a.Name())}
}

func (a workspaceHasManyWorkspaceProjectList) Unscoped() *workspaceHasManyWorkspaceProjectList {
	a.db = a.db.Unscoped()
	return &a
}

type workspaceHasManyWorkspaceProjectListTx struct{ tx *gorm.Association }

func (a workspaceHasManyWorkspaceProjectListTx) Find() (result []*model.WorkspaceProject, err error) {
	return result, a.tx.Find(&result)
}

func (a workspaceHasManyWorkspaceProjectListTx) Append(values ...*model.WorkspaceProject) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a workspaceHasManyWorkspaceProjectListTx) Replace(values ...*model.WorkspaceProject) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a workspaceHasManyWorkspaceProjectListTx) Delete(values ...*model.WorkspaceProject) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a workspaceHasManyWorkspaceProjectListTx) Clear() error {
	return a.tx.Clear()
}

func (a workspaceHasManyWorkspaceProjectListTx) Count() int64 {
	return a.tx.Count()
}

func (a workspaceHasManyWorkspaceProjectListTx) Unscoped() *workspaceHasManyWorkspaceProjectListTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type workspaceHasManyWorkspaceLabelList struct {
	db *gorm.DB

	field.RelationField
}

func (a workspaceHasManyWorkspaceLabelList) Where(conds ...field.Expr) *workspaceHasManyWorkspaceLabelList {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a workspaceHasManyWorkspaceLabelList) WithContext(ctx context.Context) *workspaceHasManyWorkspaceLabelList {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a workspaceHasManyWorkspaceLabelList) Session(session *gorm.Session) *workspaceHasManyWorkspaceLabelList {
	a.db = a.db.Session(session)
	return &a
}

func (a workspaceHasManyWorkspaceLabelList) Model(m *model.Workspace) *workspaceHasManyWorkspaceLabelListTx {
	return &workspaceHasManyWorkspaceLabelListTx{a.db.Model(m).Association(a.Name())}
}

func (a workspaceHasManyWorkspaceLabelList) Unscoped() *workspaceHasManyWorkspaceLabelList {
	a.db = a.db.Unscoped()
	return &a
}

type workspaceHasManyWorkspaceLabelListTx struct{ tx *gorm.Association }

func (a workspaceHasManyWorkspaceLabelListTx) Find() (result []*model.WorkspaceLabel, err error) {
	return result, a.tx.Find(&result)
}

func (a workspaceHasManyWorkspaceLabelListTx) Append(values ...*model.WorkspaceLabel) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a workspaceHasManyWorkspaceLabelListTx) Replace(values ...*model.WorkspaceLabel) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a workspaceHasManyWorkspaceLabelListTx) Delete(values ...*model.WorkspaceLabel) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a workspaceHasManyWorkspaceLabelListTx) Clear() error {
	return a.tx.Clear()
}

func (a workspaceHasManyWorkspaceLabelListTx) Count() int64 {
	return a.tx.Count()
}

func (a workspaceHasManyWorkspaceLabelListTx) Unscoped() *workspaceHasManyWorkspaceLabelListTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type workspaceDo struct{ gen.DO }

type IWorkspaceDo interface {
	gen.SubQuery
	Debug() IWorkspaceDo
	WithContext(ctx context.Context) IWorkspaceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWorkspaceDo
	WriteDB() IWorkspaceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWorkspaceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWorkspaceDo
	Not(conds ...gen.Condition) IWorkspaceDo
	Or(conds ...gen.Condition) IWorkspaceDo
	Select(conds ...field.Expr) IWorkspaceDo
	Where(conds ...gen.Condition) IWorkspaceDo
	Order(conds ...field.Expr) IWorkspaceDo
	Distinct(cols ...field.Expr) IWorkspaceDo
	Omit(cols ...field.Expr) IWorkspaceDo
	Join(table schema.Tabler, on ...field.Expr) IWorkspaceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWorkspaceDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWorkspaceDo
	Group(cols ...field.Expr) IWorkspaceDo
	Having(conds ...gen.Condition) IWorkspaceDo
	Limit(limit int) IWorkspaceDo
	Offset(offset int) IWorkspaceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWorkspaceDo
	Unscoped() IWorkspaceDo
	Create(values ...*model.Workspace) error
	CreateInBatches(values []*model.Workspace, batchSize int) error
	Save(values ...*model.Workspace) error
	First() (*model.Workspace, error)
	Take() (*model.Workspace, error)
	Last() (*model.Workspace, error)
	Find() ([]*model.Workspace, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Workspace, err error)
	FindInBatches(result *[]*model.Workspace, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Workspace) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWorkspaceDo
	Assign(attrs ...field.AssignExpr) IWorkspaceDo
	Joins(fields ...field.RelationField) IWorkspaceDo
	Preload(fields ...field.RelationField) IWorkspaceDo
	FirstOrInit() (*model.Workspace, error)
	FirstOrCreate() (*model.Workspace, error)
	FindByPage(offset int, limit int) (result []*model.Workspace, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWorkspaceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w workspaceDo) Debug() IWorkspaceDo {
	return w.withDO(w.DO.Debug())
}

func (w workspaceDo) WithContext(ctx context.Context) IWorkspaceDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w workspaceDo) ReadDB() IWorkspaceDo {
	return w.Clauses(dbresolver.Read)
}

func (w workspaceDo) WriteDB() IWorkspaceDo {
	return w.Clauses(dbresolver.Write)
}

func (w workspaceDo) Session(config *gorm.Session) IWorkspaceDo {
	return w.withDO(w.DO.Session(config))
}

func (w workspaceDo) Clauses(conds ...clause.Expression) IWorkspaceDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w workspaceDo) Returning(value interface{}, columns ...string) IWorkspaceDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w workspaceDo) Not(conds ...gen.Condition) IWorkspaceDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w workspaceDo) Or(conds ...gen.Condition) IWorkspaceDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w workspaceDo) Select(conds ...field.Expr) IWorkspaceDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w workspaceDo) Where(conds ...gen.Condition) IWorkspaceDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w workspaceDo) Order(conds ...field.Expr) IWorkspaceDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w workspaceDo) Distinct(cols ...field.Expr) IWorkspaceDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w workspaceDo) Omit(cols ...field.Expr) IWorkspaceDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w workspaceDo) Join(table schema.Tabler, on ...field.Expr) IWorkspaceDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w workspaceDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWorkspaceDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w workspaceDo) RightJoin(table schema.Tabler, on ...field.Expr) IWorkspaceDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w workspaceDo) Group(cols ...field.Expr) IWorkspaceDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w workspaceDo) Having(conds ...gen.Condition) IWorkspaceDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w workspaceDo) Limit(limit int) IWorkspaceDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w workspaceDo) Offset(offset int) IWorkspaceDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w workspaceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWorkspaceDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w workspaceDo) Unscoped() IWorkspaceDo {
	return w.withDO(w.DO.Unscoped())
}

func (w workspaceDo) Create(values ...*model.Workspace) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w workspaceDo) CreateInBatches(values []*model.Workspace, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w workspaceDo) Save(values ...*model.Workspace) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w workspaceDo) First() (*model.Workspace, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Workspace), nil
	}
}

func (w workspaceDo) Take() (*model.Workspace, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Workspace), nil
	}
}

func (w workspaceDo) Last() (*model.Workspace, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Workspace), nil
	}
}

func (w workspaceDo) Find() ([]*model.Workspace, error) {
	result, err := w.DO.Find()
	return result.([]*model.Workspace), err
}

func (w workspaceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Workspace, err error) {
	buf := make([]*model.Workspace, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w workspaceDo) FindInBatches(result *[]*model.Workspace, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w workspaceDo) Attrs(attrs ...field.AssignExpr) IWorkspaceDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w workspaceDo) Assign(attrs ...field.AssignExpr) IWorkspaceDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w workspaceDo) Joins(fields ...field.RelationField) IWorkspaceDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w workspaceDo) Preload(fields ...field.RelationField) IWorkspaceDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w workspaceDo) FirstOrInit() (*model.Workspace, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Workspace), nil
	}
}

func (w workspaceDo) FirstOrCreate() (*model.Workspace, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Workspace), nil
	}
}

func (w workspaceDo) FindByPage(offset int, limit int) (result []*model.Workspace, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w workspaceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w workspaceDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w workspaceDo) Delete(models ...*model.Workspace) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *workspaceDo) withDO(do gen.Dao) *workspaceDo {
	w.DO = *do.(*gen.DO)
	return w
}
