// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"we-claude-terminal/go-server/internal/dal/model"
)

func newWorkspaceLabel(db *gorm.DB, opts ...gen.DOOption) workspaceLabel {
	_workspaceLabel := workspaceLabel{}

	_workspaceLabel.workspaceLabelDo.UseDB(db, opts...)
	_workspaceLabel.workspaceLabelDo.UseModel(&model.WorkspaceLabel{})

	tableName := _workspaceLabel.workspaceLabelDo.TableName()
	_workspaceLabel.ALL = field.NewAsterisk(tableName)
	_workspaceLabel.ID = field.NewInt(tableName, "id")
	_workspaceLabel.WorkspaceID = field.NewInt(tableName, "workspace_id")
	_workspaceLabel.Name = field.NewString(tableName, "name")
	_workspaceLabel.Color = field.NewString(tableName, "color")
	_workspaceLabel.Description = field.NewString(tableName, "description")
	_workspaceLabel.SortOrder = field.NewFloat64(tableName, "sort_order")
	_workspaceLabel.CreatedAt = field.NewTime(tableName, "created_at")
	_workspaceLabel.UpdatedAt = field.NewTime(tableName, "updated_at")
	_workspaceLabel.DeletedAt = field.NewField(tableName, "deleted_at")

	_workspaceLabel.fillFieldMap()

	return _workspaceLabel
}

type workspaceLabel struct {
	workspaceLabelDo workspaceLabelDo

	ALL         field.Asterisk
	ID          field.Int
	WorkspaceID field.Int
	Name        field.String
	Color       field.String
	Description field.String
	SortOrder   field.Float64
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field

	fieldMap map[string]field.Expr
}

func (w workspaceLabel) Table(newTableName string) *workspaceLabel {
	w.workspaceLabelDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w workspaceLabel) As(alias string) *workspaceLabel {
	w.workspaceLabelDo.DO = *(w.workspaceLabelDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *workspaceLabel) updateTableName(table string) *workspaceLabel {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewInt(table, "id")
	w.WorkspaceID = field.NewInt(table, "workspace_id")
	w.Name = field.NewString(table, "name")
	w.Color = field.NewString(table, "color")
	w.Description = field.NewString(table, "description")
	w.SortOrder = field.NewFloat64(table, "sort_order")
	w.CreatedAt = field.NewTime(table, "created_at")
	w.UpdatedAt = field.NewTime(table, "updated_at")
	w.DeletedAt = field.NewField(table, "deleted_at")

	w.fillFieldMap()

	return w
}

func (w *workspaceLabel) WithContext(ctx context.Context) IWorkspaceLabelDo {
	return w.workspaceLabelDo.WithContext(ctx)
}

func (w workspaceLabel) TableName() string { return w.workspaceLabelDo.TableName() }

func (w workspaceLabel) Alias() string { return w.workspaceLabelDo.Alias() }

func (w workspaceLabel) Columns(cols ...field.Expr) gen.Columns {
	return w.workspaceLabelDo.Columns(cols...)
}

func (w *workspaceLabel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *workspaceLabel) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 9)
	w.fieldMap["id"] = w.ID
	w.fieldMap["workspace_id"] = w.WorkspaceID
	w.fieldMap["name"] = w.Name
	w.fieldMap["color"] = w.Color
	w.fieldMap["description"] = w.Description
	w.fieldMap["sort_order"] = w.SortOrder
	w.fieldMap["created_at"] = w.CreatedAt
	w.fieldMap["updated_at"] = w.UpdatedAt
	w.fieldMap["deleted_at"] = w.DeletedAt
}

func (w workspaceLabel) clone(db *gorm.DB) workspaceLabel {
	w.workspaceLabelDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w workspaceLabel) replaceDB(db *gorm.DB) workspaceLabel {
	w.workspaceLabelDo.ReplaceDB(db)
	return w
}

type workspaceLabelDo struct{ gen.DO }

type IWorkspaceLabelDo interface {
	gen.SubQuery
	Debug() IWorkspaceLabelDo
	WithContext(ctx context.Context) IWorkspaceLabelDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWorkspaceLabelDo
	WriteDB() IWorkspaceLabelDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWorkspaceLabelDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWorkspaceLabelDo
	Not(conds ...gen.Condition) IWorkspaceLabelDo
	Or(conds ...gen.Condition) IWorkspaceLabelDo
	Select(conds ...field.Expr) IWorkspaceLabelDo
	Where(conds ...gen.Condition) IWorkspaceLabelDo
	Order(conds ...field.Expr) IWorkspaceLabelDo
	Distinct(cols ...field.Expr) IWorkspaceLabelDo
	Omit(cols ...field.Expr) IWorkspaceLabelDo
	Join(table schema.Tabler, on ...field.Expr) IWorkspaceLabelDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWorkspaceLabelDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWorkspaceLabelDo
	Group(cols ...field.Expr) IWorkspaceLabelDo
	Having(conds ...gen.Condition) IWorkspaceLabelDo
	Limit(limit int) IWorkspaceLabelDo
	Offset(offset int) IWorkspaceLabelDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWorkspaceLabelDo
	Unscoped() IWorkspaceLabelDo
	Create(values ...*model.WorkspaceLabel) error
	CreateInBatches(values []*model.WorkspaceLabel, batchSize int) error
	Save(values ...*model.WorkspaceLabel) error
	First() (*model.WorkspaceLabel, error)
	Take() (*model.WorkspaceLabel, error)
	Last() (*model.WorkspaceLabel, error)
	Find() ([]*model.WorkspaceLabel, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WorkspaceLabel, err error)
	FindInBatches(result *[]*model.WorkspaceLabel, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.WorkspaceLabel) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWorkspaceLabelDo
	Assign(attrs ...field.AssignExpr) IWorkspaceLabelDo
	Joins(fields ...field.RelationField) IWorkspaceLabelDo
	Preload(fields ...field.RelationField) IWorkspaceLabelDo
	FirstOrInit() (*model.WorkspaceLabel, error)
	FirstOrCreate() (*model.WorkspaceLabel, error)
	FindByPage(offset int, limit int) (result []*model.WorkspaceLabel, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWorkspaceLabelDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w workspaceLabelDo) Debug() IWorkspaceLabelDo {
	return w.withDO(w.DO.Debug())
}

func (w workspaceLabelDo) WithContext(ctx context.Context) IWorkspaceLabelDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w workspaceLabelDo) ReadDB() IWorkspaceLabelDo {
	return w.Clauses(dbresolver.Read)
}

func (w workspaceLabelDo) WriteDB() IWorkspaceLabelDo {
	return w.Clauses(dbresolver.Write)
}

func (w workspaceLabelDo) Session(config *gorm.Session) IWorkspaceLabelDo {
	return w.withDO(w.DO.Session(config))
}

func (w workspaceLabelDo) Clauses(conds ...clause.Expression) IWorkspaceLabelDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w workspaceLabelDo) Returning(value interface{}, columns ...string) IWorkspaceLabelDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w workspaceLabelDo) Not(conds ...gen.Condition) IWorkspaceLabelDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w workspaceLabelDo) Or(conds ...gen.Condition) IWorkspaceLabelDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w workspaceLabelDo) Select(conds ...field.Expr) IWorkspaceLabelDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w workspaceLabelDo) Where(conds ...gen.Condition) IWorkspaceLabelDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w workspaceLabelDo) Order(conds ...field.Expr) IWorkspaceLabelDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w workspaceLabelDo) Distinct(cols ...field.Expr) IWorkspaceLabelDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w workspaceLabelDo) Omit(cols ...field.Expr) IWorkspaceLabelDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w workspaceLabelDo) Join(table schema.Tabler, on ...field.Expr) IWorkspaceLabelDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w workspaceLabelDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWorkspaceLabelDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w workspaceLabelDo) RightJoin(table schema.Tabler, on ...field.Expr) IWorkspaceLabelDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w workspaceLabelDo) Group(cols ...field.Expr) IWorkspaceLabelDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w workspaceLabelDo) Having(conds ...gen.Condition) IWorkspaceLabelDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w workspaceLabelDo) Limit(limit int) IWorkspaceLabelDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w workspaceLabelDo) Offset(offset int) IWorkspaceLabelDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w workspaceLabelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWorkspaceLabelDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w workspaceLabelDo) Unscoped() IWorkspaceLabelDo {
	return w.withDO(w.DO.Unscoped())
}

func (w workspaceLabelDo) Create(values ...*model.WorkspaceLabel) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w workspaceLabelDo) CreateInBatches(values []*model.WorkspaceLabel, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w workspaceLabelDo) Save(values ...*model.WorkspaceLabel) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w workspaceLabelDo) First() (*model.WorkspaceLabel, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkspaceLabel), nil
	}
}

func (w workspaceLabelDo) Take() (*model.WorkspaceLabel, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkspaceLabel), nil
	}
}

func (w workspaceLabelDo) Last() (*model.WorkspaceLabel, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkspaceLabel), nil
	}
}

func (w workspaceLabelDo) Find() ([]*model.WorkspaceLabel, error) {
	result, err := w.DO.Find()
	return result.([]*model.WorkspaceLabel), err
}

func (w workspaceLabelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WorkspaceLabel, err error) {
	buf := make([]*model.WorkspaceLabel, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w workspaceLabelDo) FindInBatches(result *[]*model.WorkspaceLabel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w workspaceLabelDo) Attrs(attrs ...field.AssignExpr) IWorkspaceLabelDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w workspaceLabelDo) Assign(attrs ...field.AssignExpr) IWorkspaceLabelDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w workspaceLabelDo) Joins(fields ...field.RelationField) IWorkspaceLabelDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w workspaceLabelDo) Preload(fields ...field.RelationField) IWorkspaceLabelDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w workspaceLabelDo) FirstOrInit() (*model.WorkspaceLabel, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkspaceLabel), nil
	}
}

func (w workspaceLabelDo) FirstOrCreate() (*model.WorkspaceLabel, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkspaceLabel), nil
	}
}

func (w workspaceLabelDo) FindByPage(offset int, limit int) (result []*model.WorkspaceLabel, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w workspaceLabelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w workspaceLabelDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w workspaceLabelDo) Delete(models ...*model.WorkspaceLabel) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *workspaceLabelDo) withDO(do gen.Dao) *workspaceLabelDo {
	w.DO = *do.(*gen.DO)
	return w
}
